domain-models-runtime/src/main/java/org/folio/rest/persist/MongoCRUD.java
domain-models-runtime/src/test/java/org/folio/DemoRamlRestTest.java

The current code binds the embedded mongo to all IP addresses. This triggers windows firewall popups.
To have the popup only one time UserTempNaming() has been used.
The better solution is to restrict bindIp to localhost.

use Net(bindIp="localhost", ...) to avoid windows firewall popup

---

domain-models-runtime/pom.xml

This has the additional benefit that `mvn install` works without internet connection (if branch dmod-75 also gets applied).

use codestyles.xml of current branch, not from master

---

domain-models-runtime/pom.xml
domain-models-runtime/src/main/java/org/folio/rest/tools/messages/Messages.java
domain-models-runtime/src/main/resources/infra-messages/APIMessages_de.properties
domain-models-runtime/src/main/resources/infra-messages/APIMessages_en.properties
domain-models-runtime/src/test/java/org/folio/rest/tools/MessagesTest.java

maven: copy .properties using ISO-8859-1
use standard file name schema (APIMessages_en.properties) to help translation toolchain and trigger IDEs to encode them correctly
accept old file name schema during transition time
add German translation

fix .properties files

---

domain-models-api-interfaces/pom.xml
domain-models-interface-extensions/pom.xml
domain-models-runtime/pom.xml
rules/pom.xml

Build fails with `[FATAL] Non-resolvable parent POM for org.folio:rules:[unknown-version]: Could not find artifact org.folio:raml-module-builder:pom:2.2.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 3, column 11` after .m2 directory is removed.

completely update pom versions to 2.2.2-SNAPSHOT

---

domain-models-runtime/pom.xml

With this commit we no longer have warnings from the shade plugin about overlapping classes. See DMOD-28

Exclude classes from jaxb-xjc already in com.sun.codemodel:codemodel

---

domain-models-runtime/src/main/java/org/folio/rest/tools/utils/OutStream.java
domain-models-runtime/src/test/java/org/folio/rest/tools/utils/OutStreamTest.java

* add unit tests
* add javadoc
* fix UTF_8 bug with default charset
* remove BufferedWriter/OutputStreamWriter, no buffering needed for a single write

DMOD-161: OutStream unit tests, fix UTF_8

---

README.md
domain-models-interface-extensions/pom.xml
domain-models-interface-extensions/src/main/java/org/folio/rest/tools/MDGenerator.java
domain-models-interface-extensions/src/main/java/org/folio/rest/tools/utils/Envs.java

Bash doesn't allow environment variables like db.host that contain a dot. Therefore replacing dot by underscore. Converting to the usual uppercase.
allDBConfs() also returns the values from deprecated variables with dot.

DMOD-165 fix db. DB_ environment variables

---

codestyles.xml

Change Checkstyle's NewlineAtEndOfFile from system to lf to match .editorconfig's end_of_line = lf

FOLIO-351 NewlineAtEndOfFile=lf

---

domain-models-interface-extensions/src/main/java/org/folio/rest/tools/ClientGenerator.java
domain-models-runtime/src/main/java/org/folio/rest/tools/client/HttpModuleClient.java
domain-models-runtime/src/main/java/org/folio/rest/tools/utils/VertxUtils.java

* Extract duplicated code into function getVertxFromContextOrNew().
* Reduce number of lines of constructor generated by ClientGenerator from 21 below 20 to comply with coding guidelines.

DMOD-161 extract VertxUtils.getVertxFromContextOrNew()

---

domain-models-api-interfaces/raml/book.schema
domain-models-api-interfaces/raml/sample.raml

In sample.raml
Fix some old errors that cluttered the raml-cop output.
Fixed the schema $ref to metadata.schema
This is an example of RMB-30.
Because we have the raml-util local, it is easy to link to with a relative reference with no dot-dots.

FOLIO-601 fix raml 1

---

domain-models-runtime/pom.xml
domain-models-runtime/src/main/java/org/folio/rest/persist/PostgresClient.java
pom.xml
postgres-runner/pom.xml

Three security vulnerabilities have been fixed by PostgreSQL 10.1, 9.6.6, 9.5.10:
* CVE-2017-12172: Start scripts permit database administrator to modify root-owned files
* CVE-2017-15098: Memory disclosure in JSON functions
* CVE-2017-15099: INSERT ... ON CONFLICT DO UPDATE fails to enforce SELECT privileges
This PostgreSQL update also fixes a number of bugs reported in the last few months.
https://www.postgresql.org/about/news/1801/

RMB-114: Security update postgres-embedded:2.6

---

domain-models-interface-extensions/pom.xml
domain-models-interface-extensions/src/main/java/org/folio/rest/tools/AnnotationGrabber.java
domain-models-interface-extensions/src/test/java/org/folio/rest/jaxrs/resource/TestResource.java
domain-models-interface-extensions/src/test/java/org/folio/rest/tools/AnnotationGrabberTest.java
pom.xml

Fixes these major sonar bugs:
* 3 times: Use an "instanceof" or "Class.isAssignableFrom()" instead of .equals(type.getName()).
* A "NullPointerException" could be thrown; "prevObjForDefaultVal" is nullable here.

AnnotationGrabber: Fix major bugs (Null, instanceof), add unit test.

---

domain-models-api-interfaces/ramls/admin.raml
domain-models-api-interfaces/ramls/examples/bulk.sample
domain-models-api-interfaces/ramls/examples/bulks.sample
domain-models-api-interfaces/ramls/examples/job.sample
domain-models-api-interfaces/ramls/examples/jobs.sample
domain-models-api-interfaces/ramls/examples/jobs_conf.sample
domain-models-api-interfaces/ramls/examples/jobs_confs.sample
domain-models-api-interfaces/ramls/jobs.raml

Fix the configuration of examples.
No changes to schema.
Use exampleCollection examples.
Was using exampleItem, causing the raml-cop validation warnings.
After those messages were gone there was one actual error in the examples.
Note that for the jobs_confs.sample, the collection is named "jobs_confs" in the raml file, but "job_confs" in the schema.
Made this example match its schema.

FOLIO-601 fix raml 2

---

pom.xml

Use vertx-stack-depchain.
mod-users and mod-inventory-storage build with this change.
mod-configuration build with this change if you update vertx-unit to 3.5.1.

RMB-143: Version update: vertx 3.5.1, jackson 2.9.4

---

domain-models-runtime/pom.xml

This is a patched version from Vert.x 3.5.1 that releases unused
connections after 1 minute (in any pool).

Use vertx-mysql-postgresql-client-3.5.1-FOLIO.1 RMB-154

---

domain-models-interface-extensions/src/main/java/org/folio/rest/tools/plugins/ResourceMethodExtensionPlugin.java

Part of RMB-208 work, but we still don't get annotations for
queryparameters from RAML.

Add @Annotate to generated classes

---

domain-models-runtime/pom.xml

Update to cql2pg-json 2.2.3 that contains these fixes:
* CQLPG-55: Trim trailing space and loose * that breaks fulltext search.
* CQLPG-54: Use the 'simple' dictionary for fulltext instead of 'english', to get around stopwords.

RMB-250: cql2pgjson 2.2.3: Fix fulltext search

---

domain-models-api-interfaces/ramls/README.md

This old README was trying to explain the $ref complications pre-RMBv20
——
Also triggering a test of the lint-raml CI:
The lint-raml CI job now logs errors for missing JSON schema description fields.
So will now display the messages via the GitHub PR screen.
It does not cause the Jenkins build stage to fail. It will just show the errors.
FOLIO-1447

Remove old ramls README RMB-203

---

domain-models-runtime/pom.xml

vertx-mysql-postgresql-client:3.5.1-FOLIO.1

RMB-262: Disable warning "Overriding managed version 3.5.1" in pom.xml

---

domain-models-api-interfaces/ramls/admin.raml
domain-models-api-interfaces/ramls/jobs.raml
domain-models-api-interfaces/ramls/sample.raml
domain-models-runtime/pom.xml

Enables http.port to be set for whatever port the local development server is using for this module.

RMB-280 configure local apidocs

---

domain-models-runtime/src/main/java/org/folio/rest/RestVerticle.java

In mod-kb-ebsco-java, we use JSON API with content type application/vnd.api+json and while RMB PUT supports all content types, currently POST consumes only a subset of those content types and does not support 'application/vnd.api+json' due  to which we are getting the following error:
```org.folio.rest.RestVerticle
SEVERE: HV000116: The object to be validated must not be null.
java.lang.IllegalArgumentException: HV000116: The object to be validated must not be null.
at org.hibernate.validator.internal.util.Contracts.assertNotNull(Contracts.java:41)
at org.hibernate.validator.internal.engine.ValidatorImpl.validate(ValidatorImpl.java:190)
at org.folio.rest.RestVerticle.isValidRequest(RestVerticle.java:1458)```
This PR hopefully should fix the above.

Add support for application/vnd.api+json content type for POST requests

---

domain-models-runtime/src/main/java/org/folio/rest/RestVerticle.java
domain-models-runtime/src/test/java/org/folio/rest/RestVerticleTest.java
domain-models-runtime/src/test/java/org/folio/rest/jaxrs/model/CalendarPeriodsServicePointIdCalculateopeningGetUnit.java

This is not an elegant solution. The name method of the enum should
instead be invoked to match ...

Fix enun values not matched RMB-308

---

pom.xml

Fixes
* https://nvd.nist.gov/vuln/detail/CVE-2018-19360
* https://nvd.nist.gov/vuln/detail/CVE-2018-19361
* https://nvd.nist.gov/vuln/detail/CVE-2018-19362
* https://nvd.nist.gov/vuln/detail/CVE-2018-1000873

RMB-315: Fix security vulnerabilities: jackson-databind 2.9.8.

---

domain-models-runtime/src/main/java/org/folio/rest/RestVerticle.java
domain-models-runtime/src/test/java/org/folio/rest/RestVerticleTest.java
pom.xml

There was a bug report about an old java version on slack in #mod-circulation-dev yesterday.
This runtime check will give a good error message for all modules that use rmb.
At some time in future we will require java 11 where this will be useful.

Minimum java version runtime check.

---

domain-models-runtime/pom.xml

This reverts commit e0fb76962ed076a5e4361c38e20c2683532c9890.
This disables running JUnit tests in Eclipse.
This reenables running integration tests when invoking mvn install.
A proper solution will be done at a later time:
https://issues.folio.org/browse/RMB-351
"Enable Junit4 + Junit5 and make it work in Eclipse"

RMB-350: Revert "Enable JUnit5 in Eclipse." Fix "PgUtilIT not tested"

---

domain-models-runtime-it/ramls/bee.json
domain-models-runtime-it/ramls/myitem.json

The "required" property must have elements.
So remove it entirely when intended to be empty.

Remove empty JSON "required" property

---

domain-models-runtime/src/main/java/org/folio/rest/persist/PostgresClient.java
domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientTest.java

This fixes the code to dig out the query for "Counting". The original query returned by CQL2pgJSON is corrupted. Actually, re-parsing SQL is a very bad idea. Eventually, the Cql2PG should return a "SQL" object where the where-clause (WITHOUT "where") and sorting are separate entities so they can be shuffled around for later usage.

Adjust count query RMB-422

---

domain-models-runtime/src/main/resources/templates/facets/base_facet_query.ftl
domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientTest.java

To fix RMB-437 where user group facets search failed due to collision between select alias and existing table column name.

Use field path over alias to avoid collision

---

pom.xml

CVE-2019-14379, CVE-2019-14439

RMB-442: jackson-databind 2.9.9.2, fixes 2 security vulnerabilities

---

README.md
dbschema/src/main/java/org/folio/rest/persist/ddlgen/Script.java
dbschema/src/test/java/org/folio/rest/tools/utils/ObjectMapperToolTest.java
dbschema/src/test/resources/schema.json
domain-models-runtime/src/main/resources/templates/db_scripts/main.ftl
domain-models-runtime/src/test/java/org/folio/rest/persist/ddlgen/SchemaMakerTest.java
domain-models-runtime/src/test/resources/templates/db_scripts/script.sql
domain-models-runtime/src/test/resources/templates/db_scripts/scriptWithSnippetPath.json
domain-models-runtime/src/test/resources/templates/db_scripts/scriptWithSnippetPathAndSnippet.json

Associated jira: https://issues.folio.org/browse/RMB-460. 
Currently some modules have "snippet" set to a very long sql script, that is difficult to read on one line (e.g. https://github.com/folio-org/mod-notes/blob/master/src/main/resources/templates/db_scripts/schema.json). Modules often store a readable version in a separate sql file alongside schema.json, so it would prevent duplication if we could reference sql files directly.

RMB-460: Add an option to specify path to sql script file

---

domain-models-interface-extensions/src/main/java/org/folio/rest/tools/utils/Envs.java
domain-models-interface-extensions/src/test/java/org/folio/rest/tools/utils/EnvsTest.java

* Breaking change for the database config environment variables.
* Report environment variable name if parsing int fails.

RMB-318: Drop deprecated dot (db.port) variables, use underscore (DB_PORT)

---

README.md
domain-models-runtime-it/src/main/resources/templates/db_scripts/schema.json
domain-models-runtime/pom.xml
domain-models-runtime/src/main/java/org/folio/rest/persist/ddlgen/SchemaMaker.java
domain-models-runtime/src/main/resources/templates/db_scripts/foreign_keys.ftl
domain-models-runtime/src/test/java/org/folio/rest/persist/ddlgen/SchemaMakerIT.java
domain-models-runtime/src/test/resources/templates/db_scripts/schemaInstanceItem.json

A foreign key "targetPath" entry does not have a "fieldName" property.
This results in an unexpected null value in SchemaMaker.java and foreign_keys.ftl SQL generation.
Fix: Skip those entries.

RMB-451: Fix SchemaMaker foreign key targetPath

---

doc/upgrading.md

It was important to get the recent upgrading notes addition (pull/#511) published quickly because v27 already released.
This is a suggested improvement. Doing `git add` rather than commit enables the updated submodule to be tested without mvn interference.
And linked to dev docs.

Improve git submodule advice

---

README.md
cql2pgjson/src/main/java/org/folio/cql2pgjson/CQL2PgJSON.java
cql2pgjson/src/main/java/org/folio/cql2pgjson/model/DbIndex.java
cql2pgjson/src/main/java/org/folio/cql2pgjson/util/DbSchemaUtils.java
cql2pgjson/src/test/java/org/folio/cql2pgjson/CQL2PgJSONTest.java
cql2pgjson/src/test/java/org/folio/cql2pgjson/ForeignKeyGenerationTest.java
cql2pgjson/src/test/resources/jo-ka-lea.sql
cql2pgjson/src/test/resources/templates/db_scripts/schema.json
cql2pgjson/src/test/resources/users.sql
doc/upgrading.md
domain-models-runtime/src/main/resources/templates/db_scripts/foreign_keys.ftl

Always create an index for the foreign key table field that has been extracted from
the jsonb. This UUID index is smaller and faster than an index that extracts the UUID
string from the jsonb object.
Change all queries to use that field and index, for example use users.groupId in favour
of users.jsonb->>'groupId'.

RMB-468: Foreign key field index

---

README.md
domain-models-interface-extensions/src/main/java/org/folio/rest/tools/utils/Envs.java
domain-models-interface-extensions/src/test/java/org/folio/rest/tools/utils/EnvsTest.java
domain-models-runtime/src/main/java/org/folio/rest/persist/PostgresClient.java
domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientTest.java
domain-models-runtime/src/test/resources/my-postgres-conf.json

I forgot to enable connectionReleaseDelay in RMB-485.
* Use 1 minute delay as default (the same default we had before: https://github.com/folio-org/vertx-mysql-postgresql-client/blob/release-connection-pool-3-5-1-folio-1/src/main/java/io/vertx/ext/asyncsql/impl/pool/AsyncConnectionPool.java#L52 ).
* Allow DB_CONNECTIONRELEASEDELAY environment variable to overwrite the default.
* Document this in RMB README.

RMB-496: connectionReleaseDelay: Use 1 minute as default, add config

---

pom.xml

Three serialization gadget (= polymorphic typing) security vulnerability issues have been reported against jackson-databind versions before 2.9.10.1:
jackson-databind 2.9.10.1 (released 2019-10-20) fixes
* commons-dbcp, p6spy (https://nvd.nist.gov/vuln/detail/CVE-2019-16942 / https://nvd.nist.gov/vuln/detail/CVE-2019-16943 = https://github.com/FasterXML/jackson-databind/issues/2478
* log4j-extras/1.2 (https://nvd.nist.gov/vuln/detail/CVE-2019-17531 = https://github.com/FasterXML/jackson-databind/issues/2498)
jackson-databind 2.9.10.2 (https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.9#micro-patches) (not yet released) fixes
* ehcache/JNDI (CVEs to be allocated = https://github.com/FasterXML/jackson-databind/issues/2526)
See also
* …

RMB-504: Jackson-* version 2.10.0, fixes jackson-databind security.

---

domain-models-runtime/pom.xml
domain-models-runtime/src/main/java/org/folio/rest/RestVerticle.java
postgres-runner/pom.xml
rules/pom.xml
rules/src/main/java/org/folio/rulez/RuleTracker.java

This is because we're using log4j as logging implementation for RMB
and we've seen calls to MDC fail in some cases when using the slf4j verion.

Use log4j's MDC rather than slf4j's MDC RMB-511

---

doc/upgrading.md
pom.xml
sample/pom.xml
sample2/pom.xml

https://nvd.nist.gov/vuln/detail/CVE-2019-16869
https://issues.folio.org/browse/RMB-529
https://issues.folio.org/browse/FOLIO-2368

RMB-529: Vert.x 3.8.4 fixing Netty HTTP request smuggling CVE-2019-16869

---

dbschema/src/main/java/org/folio/rest/persist/ddlgen/Index.java

* Remove unneccessary use of temporary StringBuilder
* Replace duplicate String constant by final variable
* Convert to guard clauses to avoid nesting/indentation
* Use line breaks for .append clauses for readability
* Reword comments
* Code formatting to comply with coding standards

RMB-471: Fix ddlgen/Index.java StringBuilder code smells

---

cql2pgjson/src/main/java/org/folio/cql2pgjson/CQL2PgJSON.java
dbschema/src/main/java/org/folio/cql2pgjson/util/Cql2PgUtil.java
dbschema/src/main/java/org/folio/rest/persist/ddlgen/Index.java
dbschema/src/test/java/org/folio/rest/persist/ddlgen/IndexTest.java
domain-models-runtime/src/test/java/org/folio/rest/persist/ddlgen/SchemaMakerTest.java

Cherry-pick from master to b29.1.
* moved wrapping into the index to create the correct index in generation and querying.
* fix for unit tests to match new function added to index code.
* added new Unit tests for code coverage.
* Revert "added new Unit tests for code coverage." This reverts commit 52917cf87d3c7e7255131e30995aec4ea9f750bd.
* updates for unit tests
* final update to unit tests for expected
* Updates for feedback

RMB-536: Missing f_unaccent for compound fields full text index (#583)

---

README.md
cql2pgjson/src/main/java/org/folio/cql2pgjson/CQL2PgJSON.java
cql2pgjson/src/test/java/org/folio/cql2pgjson/CompoundIndexTest.java
cql2pgjson/src/test/java/org/folio/cql2pgjson/ForeignKeyGenerationTest.java
dbschema/src/main/java/org/folio/rest/persist/ddlgen/Index.java
dbschema/src/test/java/org/folio/rest/persist/ddlgen/IndexTest.java
domain-models-runtime/src/main/resources/templates/db_scripts/indexes.ftl
domain-models-runtime/src/test/java/org/folio/rest/persist/ddlgen/SchemaMakerTest.java
domain-models-runtime/src/test/resources/templates/db_scripts/test_indexes.json

Merge pull request #592 from folio-org/RMB-540-unique-index-truncation

RMB-540: Unique index must not truncate to 600 characters - 29.1 backport

---

domain-models-runtime/src/main/java/org/folio/rest/RestVerticle.java
domain-models-runtime/src/test/java/org/folio/rest/RestVerticleTest.java

The current implementation logs the exception but doesn't return to the calling client.

Return with 500 status when there is an Exception in RestVerticle.route

---

pom.xml
sample/pom.xml
sample2/pom.xml

Release notes: https://github.com/vert-x3/wiki/wiki/3.8.5-Release-Notes
3.8.5 Deprecations and breaking changes: https://github.com/vert-x3/wiki/wiki/3.8.5-Deprecations-and-breaking-changes

Upgrade vert.x from 3.8.4 to 3.8.5 fixing CompositeFuture

---

domain-models-runtime/pom.xml

We created our fork 3.8.2-FOLIO-2 with two patches. These patches
have been merged upstream:
https://github.com/vert-x3/vertx-mysql-postgresql-client/pull/136
https://github.com/vert-x3/vertx-mysql-postgresql-client/pull/164
We can drop our fork and switch back to upstream releases.

RMB-562: Switch back to upstream vertx-mysql-postgresql-client

---

domain-models-runtime/pom.xml
domain-models-runtime/src/main/java/org/folio/rest/impl/TenantAPI.java
domain-models-runtime/src/main/java/org/folio/rest/persist/PostgresClient.java
domain-models-runtime/src/main/java/org/folio/rest/persist/ddlgen/SchemaMaker.java
domain-models-runtime/src/main/resources/templates/db_scripts/main.ftl
domain-models-runtime/src/test/java/org/folio/rest/impl/TenantAPIIT.java
domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientIT.java
pom.xml
postgres-runner/pom.xml

Write schema.json into rmb_internal.jsonb->>'schemaJson'
at the end of a module's tenant install or tenant upgrade.
These methods have been futurized:
* TenantAPI.postTenant
* PostgresClient.runSQLFile

RMB-590: persist schema.json in rmb_internal

---

domain-models-runtime/src/main/java/org/folio/rest/impl/TenantAPI.java
domain-models-runtime/src/test/java/org/folio/rest/impl/TenantAPIIT.java

This was requested on Slack #raml-module-builder for unit tests for DAOs.

Make TenantAPI.sqlFile public for unit tests

---

domain-models-runtime/src/main/java/org/folio/rest/impl/AdminAPI.java
domain-models-runtime/src/test/java/org/folio/rest/impl/AdminAPIIT.java

Needed to test OutStream(RowSet<Row> result) in https://issues.folio.org/browse/RMB-246
= https://github.com/folio-org/raml-module-builder/pull/640
* Fix wrong getInstance(vertxContext.owner(), "public")
* Fix client_addr type (convert to text)
* Fix failures caused by null values in pg_ tables
* Fix division by zero
* Add database related AdminAPIIT tests

Add AdminAPIIT test, fix AdminAPI bugs

---

domain-models-runtime/src/main/resources/templates/db_scripts/main.ftl
domain-models-runtime/src/test/java/org/folio/rest/persist/ddlgen/SchemaMakerIT.java

No longer incorrectly replace `public.gin_trgm_ops` by `${myuniversity}_${mymodule}.gin_trgm_ops`.
Replace all public.* occurrence, not only the first one, and add unit test for this.

RMB-607: ${myuniversity}_${mymodule}.gin_trgm_ops

---

NEWS.md
domain-models-runtime/src/main/resources/templates/db_scripts/main.ftl
domain-models-runtime/src/main/resources/templates/db_scripts/prepare-f_unaccent-indexes.ftl
domain-models-runtime/src/test/java/org/folio/rest/persist/ddlgen/SchemaMakerIT.java

[RMB-587](https://issues.folio.org/browse/RMB-587)
Prepare new f_unaccent indexes in addition
to the existing indexes. This takes some time, but this time is saved when upgrading the module to RMB >= 29.4 (Goldenrod). Upgrade to RMB 29.3.3 to create these indexes in advance, for example at night a few days before the module upgrade to Goldenrod.
The new indexes have the _p name suffix and are updated on CRUD operations of the underlying data.
When upgrading to RMB >= 29.4 the old index is deleted and replaced by the new index, this is a fast index rename without index recreation.

RMB-587: Prepare f_unaccent indexes

---

dbschema/src/main/java/org/folio/rest/persist/ddlgen/ForeignKeys.java
domain-models-runtime/src/main/java/org/folio/rest/impl/TenantAPI.java
domain-models-runtime/src/main/java/org/folio/rest/persist/ddlgen/SchemaMaker.java
domain-models-runtime/src/main/resources/templates/db_scripts/foreign_keys.ftl
domain-models-runtime/src/main/resources/templates/db_scripts/main.ftl
domain-models-runtime/src/test/java/org/folio/rest/impl/TenantAPIIT.java
domain-models-runtime/src/test/java/org/folio/rest/persist/ddlgen/SchemaMakerTest.java
domain-models-runtime/src/test/java/org/folio/rest/tools/client/HttpModuleClient2Test.java
domain-models-runtime/src/test/resources/templates/db_scripts/foreignKey1.json
domain-models-runtime/src/test/resources/templates/db_scripts/foreignKey2.json
domain-models-runtime/src/test/resources/templates/db_scripts/indexUpgrade.json

* SchemaMaker: new previousSchema variable, can trigger deletion of tables and foreign keys
* foreign_keys.ftl: Only create foreign key trigger if an "ADD" foreign key entry exists
* foreign_keys.ftl: Don't drop auditing table when auditing table name is null
* SchemaMakerTest: Extract duplicate code into schema and schemaMaker methods.
* TenantAPI: Use schema.json comparison for upgrades.

RMB-569: Upgrade using schema.json comparison

---

doc/upgrading.md
domain-models-runtime/src/main/java/org/folio/rest/persist/PgExceptionFacade.java
domain-models-runtime/src/main/java/org/folio/rest/persist/PgExceptionUtil.java
domain-models-runtime/src/test/java/org/folio/rest/persist/PgExceptionFacadeTest.java
domain-models-runtime/src/test/java/org/folio/rest/persist/PgExceptionUtilTest.java

Use all fields: message, detail, SQL error code, severity.
PgException.getMessage() only returns the message field.

RMB-622: PgExceptionUtil.getMessage: Compose a message of all fields

---

doc/upgrading.md

Sort related issues for readability.
Merge duplicate issues.
Fix typos, punctuation, wording.

Cleanup vertx-pg-client upgrading notes

---

doc/upgrading.md
pom.xml
sample/pom.xml
sample2/pom.xml

Upgrade Vert.x to the latest released version 3.9.1 that contains several
bug fixes:
* https://github.com/vert-x3/wiki/wiki/3.9.1-Release-Notes
* https://github.com/vert-x3/wiki/wiki/3.9.1-Deprecations-and-breaking-changes
Add to upgrading notes
* Upgrade to Vert.x 3.9.1
* Using vertx-stack-depchain
* Dropping unused jackson-databind dependency

Upgrade Vert.x 3.9.1; mention vertx-stack-depchain, jackson

---

domain-models-runtime/src/main/java/org/folio/rest/persist/ddlgen/SchemaMaker.java
domain-models-runtime/src/test/java/org/folio/rest/persist/ddlgen/SchemaMakerTest.java

If fieldName is null compare targetPath to match old foreignKey and new foreignKey entry.
This avoids any NullPointerException.

RMB-632: Tenant upgrade fails on foreignKey targetPath

---

domain-models-runtime/src/main/java/org/folio/rest/RestVerticle.java

It is misleading to use getOrCreateContext().
Verticle and AbstractVerticle ensure that context is always set.
https://vertx.io/docs/apidocs/io/vertx/core/AbstractVerticle.html
says: "This class also maintains references to the Vertx and
Context instances of the verticle for easy access."

Replace vertx.getOrCreateContext() by AbstractVerticle's context

---

domain-models-runtime/src/main/java/org/folio/rest/persist/PgUtil.java

The original parameter order of PgUtil.streamGet was
* routingContext, okapiHeaders, vertxContext
FOLIO-2625 changed some streamGet methods to
* okapiHeaders, vertxContext, routingContext
Undo this parameter reordering for consistency and easy upgrade
for modules based on RMB.

RMB-638: Revert PgUtil.streamGet parameter reordering

---

domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientIT.java
domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientTest.java

* Move test from PostgresClientIT to PostgresClientTest because
it is a unit test that does not require a database connection.
* Set Envs to no longer fail the test when DB_ environment variables
point to an external database to be used by integration tests.
Some developers use this to avoid the startup time of embedded
postgres.
* Use getter of JsonObject instead of JsonObject#encode() that
changes when the iteration order of the underlying Map changes.

RMB-634: Fix getConnectionConfig test assumptions

---

domain-models-runtime/src/main/resources/templates/db_scripts/foreign_keys.ftl
domain-models-runtime/src/main/resources/templates/db_scripts/indexes.ftl
domain-models-runtime/src/main/resources/templates/db_scripts/main.ftl
domain-models-runtime/src/main/resources/templates/db_scripts/rmb_internal_index.ftl

* Collect tables that need ANALYZE in rmb_internal_analyze
* At the end run ANALYZE for all of them
Prepending ${myuniversity}_${mymodule}. is no longer needed
because we set search_path.

RMB-637: Run ANALYZE after index (re-)creation

---

domain-models-runtime/src/main/resources/templates/db_scripts/foreign_keys.ftl
domain-models-runtime/src/main/resources/templates/db_scripts/main.ftl
domain-models-runtime/src/main/resources/templates/db_scripts/rmb_internal_index.ftl
domain-models-runtime/src/test/java/org/folio/rest/persist/ddlgen/SchemaMakerIT.java

No longer create duplicate foreign key constraints on upgrade.
Delete all existing duplicate foreign key constraints that
RMB < 30.0.3 has created.
Replace each case sensitive format() %I placeholder by a
case insensitive form, either %s placeholder or || concatenation,
resulting in identifier downcasing:
https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS

RMB-555: Upgrade creates duplicate foreign key constraints

---

domain-models-api-aspects/pom.xml
domain-models-runtime/pom.xml
pom.xml

* Upgrade hibernate-validator from 5.2.4.Final to 6.1.5.Final to
fix CVE-2017-7536:
https://nvd.nist.gov/vuln/detail/CVE-2017-7536
https://github.com/advisories/GHSA-xxgp-pcfc-3vgc
https://hibernate.atlassian.net/browse/HV-1498
* Adjust hibernate-validator groupId, it has moved from
org.hibernate to org.hibernate.validator
* Update all validation dependencies to latest versions:
javax.el:javax.el-api, org.javassist:javassist.
* Add org.glassfish:javax.el needed for latest hibernate-validator.
* Remove validation dependencies from domain-models-runtime,
the transitive dependency via domain-models-api-aspects
is sufficient.

RMB-648: Fix hibernate-validator privilege escalation (CVE-2017-7536)

---

domain-models-api-interfaces/ramls/sample.raml
domain-models-interface-extensions/src/main/java/org/folio/rest/tools/AnnotationGrabber.java
domain-models-interface-extensions/src/main/java/org/folio/rest/tools/RTFConsts.java
domain-models-runtime-it/pom.xml
domain-models-runtime/pom.xml
domain-models-runtime/src/test/java/org/folio/DemoRamlRestTest.java
domain-models-runtime/src/test/java/org/folio/rest/impl/BooksDemoAPI.java
pom.xml

Add org.folio.rest.jaxrs.resource.support.OPTIONS as possible HTTP
method.
Move RTFConsts.POSSIBLE_HTTP_METHOD to
AnnotationGrabber.isPossibleHttpMethod and replace substring
matching by complete string matching.
Add options API endpoint to sample.raml and a rest-assured test
for it to DemoRamlRestTest.

RMB-656: NPE at startup when an OPTIONS endpoint is defined in RAML

---

cql2pgjson-cli/pom.xml
cql2pgjson-cli/src/main/java/org/z3950/zing/cql/cql2pgjsoncli/CQL2PGCLIMain.java
cql2pgjson/pom.xml

CQL2PGCLIMain.parseDatabaseSchemaString is an internal
method (package-private) that is not used.
The package dependency org.json:json violates Apache 2.0
license because it has this incompatible license requirement:
"The Software shall be used for Good, not Evil."
https://github.com/stleary/JSON-java/blob/20200518/LICENSE
If anyone needs the functionality of the method
parseDatabaseSchemaString that is only 25 lines long it
should be re-implemented using Vert.x JsonObject or
jackson-databind.
Tasks:
* Remove method CQL2PGCLIMain.parseDatabaseSchemaString
* Remove package org.json:json from dependencies.

RMB-662: Remove parseDatabaseSchemaString and org.json:json

---

domain-models-interface-extensions/pom.xml
domain-models-runtime/pom.xml
pom.xml

Upgrade log4j from 2.9.1 to 2.13.3.
The SmtpAppender did not verify the host name matched the SSL/TLS
certificate of an SMTPS connection which could allow an attacker
with man-in-the-middle access to intercept log messages sent
through SMTPS.
This affects log4j < 2.13.2. Fix: Upgrade to log4j >= 2.13.2.
References:
https://nvd.nist.gov/vuln/detail/CVE-2020-9488
https://issues.apache.org/jira/browse/LOG4J2-2819

RMB-661: Use log4j 2.13.3 fixing SMTPS host mismatch (CVE-2020-9488)

---

pom.xml

RMB's main pom.xml `<dependencyManagement>` section downgrades
com.thoughtworks.xstream:xstream to 1.4.9.
This version contains a security bug that allows attackers
to crash the server:
* https://nvd.nist.gov/vuln/detail/CVE-2017-7957
* https://x-stream.github.io/CVE-2017-7957.html
RMB neither uses nor ships this library (`mvn dependency:tree -Dincludes=xstream`).
However, RMB `<dependencyManagement>` downgrades xstream in any
RMB based module that uses xstream.
Task: Remove xstream from pom.xml `<dependencyManagement>` section.

RMB-660: com.thoughtworks.xstream vulnerability (CVE-2017-7957)

---

README.md
cql2pgjson/src/test/java/org/folio/cql2pgjson/CQL2PgJSONTest.java

Use field match for ==, this is better wording than exact match.
Remove /respectCase and /respectAccents documentation, they
are no longer supported.
Explain that case and accent sensitivity is taken from indexes.
Remove hack for index access, we provide @-relation instead.

Explain case and accents sensitiviy, and array matching

---

cql2pgjson-cli/pom.xml
cql2pgjson/pom.xml
dbschema/pom.xml
domain-models-api-aspects/pom.xml
domain-models-api-interfaces/pom.xml
domain-models-interface-extensions/pom.xml
domain-models-runtime-it/pom.xml
domain-models-runtime/pom.xml
pom.xml
testing/pom.xml
util/pom.xml

Update plugin/library versions for upcoming JDK 11 migration. 
Leave the compile version as 1.8 in **maven-compiler-plugin**. Later on this can be switched to v11 by replacing:
```
<source>1.8</source>
<target>1.8</target>
```
with 
`<release>11</release>`
The `groupId` of `aspectj-maven-plugin` is changed from the non-maintened `org.codehaus.mojo` to the maintained fork `com.nickwongdev`. Support for the latter has been added to Intellij and Eclipse. For details see https://github.com/mojohaus/aspectj-maven-plugin/pull/45 and https://groups.google.com/forum/#!searchin/mojohaus-dev/aspectj-maven-plugin%7Csort:date

Update plugin/library versions for upcoming JDK 11 migration

---

domain-models-runtime/src/main/java/org/folio/rest/RestVerticle.java
domain-models-runtime/src/main/java/org/folio/rest/impl/TenantAPI.java
domain-models-runtime/src/main/java/org/folio/rest/tools/client/exceptions/ResponseException.java
domain-models-runtime/src/test/java/org/folio/rest/RestVerticleTest.java
domain-models-runtime/src/test/java/org/folio/rest/impl/TenantAPIIT.java

Use a ResponseException that contains a javax.ws.rs.core.Response
when a TenantAPI call fails.
The TenantAPI methods use a Handler<AsyncResult<Response>> handler
to return success and failure. It is returned as a succeeded
AsyncResult where the value is the Response:
https://github.com/folio-org/raml-module-builder/blob/v30.2.4/domain-models-runtime/src/main/java/org/folio/rest/impl/TenantAPI.java
On success the Response has a 200 or 201 HTTP status code.
If installation or upgrade fails the Response has a 400 or 500
HTTP status code and a detailed error message in the body.
Note that AsyncResult is a succeeded result in all cases.
The documentation was wrong in that it only checked the
AsyncResult (succeeded, failed) and not the Response status
code.
This is how we fix this:
A success is …

RMB-687: ResponseException for TenantAPI

---

domain-models-runtime/src/main/resources/templates/db_scripts/rmb_internal_index.ftl

The drop was forgotten in RMB-637 = PR #692 and causes
differences when comparing fresh install and upgrade.

Drop obsolete rmb_internal_index.

---

doc/upgrading.md
domain-models-runtime/pom.xml
domain-models-runtime/src/main/java/org/folio/rest/persist/PostgresClient.java
domain-models-runtime/src/main/java/org/folio/rest/persist/PreparedRowStream.java
domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientIT.java
domain-models-runtime/src/test/java/org/folio/rest/persist/PreparedRowStreamTest.java
pom.xml

Closing the prepared statement releases the resources allocated
by PostgreSQL for them and also releases the name of the prepared
statement for reuse. The latter will reduce the likelihood
of failures caused by duplicate prepared statement names reported
in https://issues.folio.org/browse/MODINVSTOR-540 :
"ERROR: prepared statement "XYZ" already exists"

RMB-693: Close prepared statements in PostgresClient stream get

---

domain-models-runtime/src/main/java/org/folio/rest/persist/ddlgen/SchemaMaker.java
domain-models-runtime/src/test/java/org/folio/rest/persist/ddlgen/SchemaMakerTest.java
domain-models-runtime/src/test/resources/templates/db_scripts/foreignKey1.json
domain-models-runtime/src/test/resources/templates/db_scripts/foreignKey2.json

Upgrading a module where the fieldName of a foreign key contains
a dot like "foo.bar" fails, the field is deleted.
Example: https://issues.folio.org/browse/CIRCSTORE-224
Fix: Apply the . to _ conversion to the previousSchema including the
foreignKeys.

RMB-694: Upgrade foreign key of a sub-field like "fieldName": "foo.bar"

---

domain-models-runtime/src/main/java/org/folio/rest/RestVerticle.java
domain-models-runtime/src/main/java/org/folio/rest/tools/utils/LogUtil.java
domain-models-runtime/src/test/java/org/folio/rest/tools/utils/LogUtilIT.java
domain-models-runtime/src/test/java/org/folio/rest/tools/utils/LogUtilTest.java

MODINVSTOR-550 reports a NullPointerException at
org.folio.rest.RestVerticle.lambda$23(RestVerticle.java:832):
```
withRequestId(rc, () -> LogUtil.formatStatsLogMessage(
rc.request().remoteAddress().toString(), rc.request().method().toString(),
rc.request().version().toString(), rc.response().getStatusCode(),
(end - start) / 1000000,
rc.response().bytesWritten(),
rc.request().path(), rc.request().query(), rc.response().getStatusMessage(), tenantId,
sb.toString()));
```
The RoutingContext rc and any of its methods may return null.
This fix handles these cases gracefully to avoid the NullPointerException.

RMB-700: NPE when RestVerticle calls LogUtil.formatStatsLogMessage

---

domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientIT.java
domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientTest.java
pom.xml

Release notes: https://github.com/vert-x3/wiki/wiki/3.9.2-Release-Notes
Most notable fix that may affect RMB based modules:
https://github.com/vert-x3/vertx-web/issues/1612 "WebClient request timeout races against send the request"

RMB-701: Update to Vert.x 3.9.2

---

domain-models-runtime/src/main/java/org/folio/rest/persist/PostgresClient.java
domain-models-runtime/src/test/java/org/folio/DemoRamlRestTest.java
domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientIT.java

PostgresClient.streamGet should close the PostgreSQL connection.
Otherwise an invalid CQL will not release the connection and
further requests will wait forever to get an available connection.

RMB-677: Close PostgreSQL connection after invalid CQL failure

---

domain-models-runtime/src/test/java/org/folio/rest/persist/ddlgen/SchemaMakerTest.java

Sonar fails the first pull request against a new branch because of two bugs:
https://github.com/folio-org/raml-module-builder/pull/755
This issue fixes the one in SchemaMakerTest.java.

RMB-705: Refactor assertThrows lambda to have only one exception

---

domain-models-runtime/src/main/java/org/folio/rest/persist/PostgresClient.java

Sonar reports this as a critical code smell issue:
Rename this constant name to match the regular expression `^[A-Z][A-Z0-9]*(_[A-Z0-9]+)*$`
```
private static final String    _PASSWORD = "password"; //NOSONAR
private static final String    _USERNAME = "username";
```
In addition the `//NOSONAR` should be replaced by a more
specific suppression using `@SuppressWarnings`, the same applies to
```
private static final String    DEFAULT_IP = "127.0.0.1"; //NOSONAR
```
that should be removed because "127.0.0.1" is an allowed hard-coded value.

RMB-706: Critical code smell constant name, hardcoded password and ip

---

domain-models-runtime/src/main/java/org/folio/rest/RestVerticle.java
domain-models-runtime/src/test/java/org/folio/rest/RestVerticleTest.java
pom.xml

We no longer need to check that the Java version is >= 1.8.0-101 because
we've already switched to Java 11 and both Maven and the Java runtime fail
with a good error message when running with Java 8.
We no longer need to detect a maven version older than 3.3 because such
versions are from 2014-12-20 or before and are unlikely to be still in use.

RMB-711: Remove Java 8 and Maven 3.3 check

---

cql2pgjson-cli/pom.xml

Remove the unused com.amazonaws:aws-lambda-java-core dependency.
Obsoletes https://github.com/folio-org/raml-module-builder/pull/762

RMB-714: Remove unused aws-lambda-java-core dependency

---

domain-models-runtime/src/main/java/org/folio/rest/impl/TenantAPI.java
domain-models-runtime/src/main/java/org/folio/rest/persist/PostgresClient.java
domain-models-runtime/src/main/resources/templates/db_scripts/delete.ftl
domain-models-runtime/src/test/java/org/folio/rest/impl/TenantAPIIT.java
domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientIT.java
domain-models-runtime/src/test/java/org/folio/rest/persist/ddlgen/SchemaMakerTest.java

After dropping schema and role the database connection still uses
the old oid. This will fail when schema and role are recreated
with the same name but a different oid.
Solution:
Close all database connections when dropping schema and role.
Other changes:
* Fix error logging (switch from System.out to log.error).
* Use schema name when calling count_estimate; this results in
a better error message: "permission problem" instead of "not found"
when permissions are missing.
* Remove "REVOKE ALL PRIVILEGES ON DATABASE postgres". This is
not needed. Even if it were needed the hard-coded database
name "postgres" may be wrong, can be "folio".
* Use "DROP ROLE" (= SQL standard) and not the PostgreSQL synonym
"DROP USER"; this parallels "CREATE ROLE".

RMB-723: Close database connection after dropping schema and role

---

domain-models-runtime/pom.xml
pom.xml

Also depend on vertx-web-client to ensure that it will be same version
as other Vert.x components used by RMB.

Update to Okapi 4.1.3 RMB-731

---

domain-models-runtime/src/main/java/org/folio/rest/persist/PgUtil.java
domain-models-runtime/src/test/java/org/folio/rest/persist/PgUtilIT.java

Sorting in CQL is expessed using the sortby keyword followed by
a list of sort-keys, each expressed as a CQL index data optionally
followed by one or more index modifiers — see
http://zing.z3950.org/cql/sorting.html#6.
For example, title/sort.descending/sort.ignorecase.
RMB handles the sort.ascending and sort.descending modifiers.
It rejects all other sort modifiers with a
CQLFeatureUnsupportedException:
https://github.com/folio-org/raml-module-builder/blob/v31.1.0/cql2pgjson/src/main/java/org/folio/cql2pgjson/model/CqlModifiers.java#L71
For optimized queries (that we use for instance.title only)
we have some lazy code that doesn't reject other sort modifiers:
https://github.com/folio-org/raml-module-builder/blob/v31.1.0/domain-models-runtime/src/main/java/org/folio/rest/persist/PgUtil.jav …

RMB-735: Reject unsupported sort modifiers in getWithOptimizedSql

---

doc/upgrading.md

This is to fix this warning issued when a module starts:
> WARNING: sun.reflect.Reflection.getCallerClass is not supported.
> This will impact performance.

Mention Multi-Release change to pom

---

domain-models-runtime/src/main/java/org/folio/rest/persist/PostgresClient.java
domain-models-runtime/src/main/java/org/folio/rest/persist/PostgresClientStreamResult.java
domain-models-runtime/src/main/java/org/folio/rest/persist/SQLConnection.java
domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientIT.java
domain-models-runtime/src/test/java/org/folio/rest/persist/SQLConnectionTest.java

closeAndHandleResult closes the connection immediately after sending
the query preventing to get more than 100 records (cursor chunk size).
Fix it by using closeAtEnd that waits until all records of
all cursor chunks have been read.

RMB-732: doStreamGetQuery returns only 100 records when limit>100

---

domain-models-runtime/src/main/java/org/folio/rest/persist/PostgresClient.java
domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientTest.java
pom.xml

Release notes: https://github.com/vert-x3/wiki/wiki/3.9.4-Release-Notes
Most notable fix:
* RowStream fetch can close prematurely the stream
https://github.com/eclipse-vertx/vertx-sql-client/issues/778
SQL Row has breaking changes that require unit tests changes:
* Row getters throw a NoSuchElementException when getting non existing column
https://github.com/eclipse-vertx/vertx-sql-client/issues/775
* Tuple/Row getters throw a ClassCastException when getting incorrect types
https://github.com/eclipse-vertx/vertx-sql-client/issues/774

RMB-738: Upgrade to Vert.x 3.9.4

---

pom.xml

The FOLIO fork https://github.com/folio-org/vertx-sql-client of the
upstream vertx-sql-client and vertx-pg-client driver contains these patches:
* https://issues.folio.org/browse/RMB-739 patch idle connection release in the forked vertx-sql-client driver
* https://issues.folio.org/browse/FOLIO-2840 Unsigned long HexSequence for name of PgPreparedStatement
Change RMB dependencies to use the forked version instead of the upstream version.

RMB-740: Use FOLIO fork of vertx-sql-client and vertx-pg-client

---

NEWS.md
cql2pgjson-cli/pom.xml
cql2pgjson/pom.xml
dbschema/pom.xml
doc/upgrading.md
domain-models-api-aspects/pom.xml
domain-models-api-interfaces/pom.xml
domain-models-interface-extensions/pom.xml
domain-models-runtime-it/pom.xml
domain-models-runtime/pom.xml
pom.xml
testing/pom.xml
util/pom.xml

* [RMB-740](https://issues.folio.org/browse/RMB-740) Use FOLIO fork of vertx-sql-client and vertx-pg-client with
the following two patches
* [RMB-739](https://issues.folio.org/browse/RMB-739) Make RMB's DB\_CONNECTIONRELEASEDELAY work again, defaults to 60 seconds
* [FOLIO-2840](https://issues.folio.org/browse/FOLIO-2840) Fix duplicate names causing 'prepared statement "XYZ" already exists'
* [RMB-738](https://issues.folio.org/browse/RMB-738) Upgrade to Vert.x 3.9.4, most notable fix: RowStream fetch
can close prematurely the stream https://github.com/eclipse-vertx/vertx-sql-client/issues/778

FOLREL-445: Release RMB v30.2.9

---

NEWS.md
cql2pgjson-cli/pom.xml
cql2pgjson/pom.xml
dbschema/pom.xml
doc/upgrading.md
domain-models-api-aspects/pom.xml
domain-models-api-interfaces/pom.xml
domain-models-interface-extensions/pom.xml
domain-models-runtime-it/pom.xml
domain-models-runtime/pom.xml
domain-models-runtime/src/main/java/org/folio/rest/persist/PostgresClient.java
domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientTest.java
pom.xml
testing/pom.xml
util/pom.xml

* [RMB-737](https://issues.folio.org/browse/RMB-737): Update to Junit and jupiter to 4.13.1
* [RMB-740](https://issues.folio.org/browse/RMB-740) Use FOLIO fork of vertx-sql-client and vertx-pg-client with
the following two patches
* [RMB-739](https://issues.folio.org/browse/RMB-739) Make RMB's DB\_CONNECTIONRELEASEDELAY work again, defaults to 60 seconds
* [FOLIO-2840](https://issues.folio.org/browse/FOLIO-2840) Fix duplicate names causing 'prepared statement "XYZ" already exists'
* [RMB-738](https://issues.folio.org/browse/RMB-738) Upgrade to Vert.x 3.9.4, most notable fixed bug: RowStream fetch
can close prematurely the stream https://github.com/eclipse-vertx/vertx-sql-client/issues/778

FOLREL-446: Release RMB 31.1.3

---

domain-models-runtime/src/main/resources/templates/db_scripts/main.ftl

This avoids "tuple concurrently updated".

RMB-744: Use "FOR UPDATE" transaction when revoking public schema privileges

---

domain-models-runtime/src/main/resources/templates/db_scripts/main.ftl

In AWS Aurora env, the db admin user cannot acquire row level lock on `pg_namespace` table due to permission issue. This PR made changes to use advisory lock.

RMB-744: Replace pg_namespace row lock with advisory lock due to permission issue

---

doc/upgrading.md

Backporting from master to b31.1
(cherry picked from commit abf281fac4291db8872a154480b27330d6f4692e)

upgrading.md: colon in timezone

---

domain-models-runtime/src/main/java/org/folio/rest/persist/PgUtil.java

Use 500 (not 400) as fall-back if 409 method is not available.
This avoids a breaking change. 500 method has been required before.

RMB-727: Revert requiring 400 status code for PgUtil.postSync

---

pom.xml

Because Okapi 4.5.0 is also using Vert.x 4.0.0.

Use okapi-common 4.5.0

---

domain-models-runtime/pom.xml
domain-models-runtime/src/main/java/org/folio/rest/persist/PostgresClient.java
domain-models-runtime/src/test/java/org/folio/DemoRamlRestTest.java
domain-models-runtime/src/test/java/org/folio/rest/impl/TenantAPIIT.java
domain-models-runtime/src/test/java/org/folio/rest/persist/PgUtilIT.java
domain-models-runtime/src/test/java/org/folio/rest/persist/RunSQLIT.java

The driver is used for testing in cql2pgjson but that's not a problem.
These public methods were removed from PostgresClient: importFile and dropCreateDatabase
dropCreateDatabase is used by mod-vendors in a number of places, but that module is archived and deprecated.
importFile is also only used by deprecated-mod-acquisitions-postgres

Remove jdbc driver from runtime RMB-642

---

README.md
domain-models-runtime/src/main/resources/templates/db_scripts/optimistic_locking.ftl

Change trigger notice level so https://github.com/folio-org/mod-inventory-storage/pull/570 can pass unit tests with embedded PostgreSQL. I was able to verify it locally. Let's try it on b32.0 branch first.

RMB-786 change OL notice level

---

pom.xml

Vertx 4.0.2 has many bug fixes, see release notes:
https://github.com/vert-x3/wiki/wiki/4.0.2-Release-Notes

RMB-799: Update Vert.x from 4.0.0 to 4.0.2

---

domain-models-runtime/src/main/java/org/folio/rest/tools/client/BuildCQL.java
domain-models-runtime/src/test/java/org/folio/rest/tools/utils/BuildCQLTest.java

BuildCQL.buildCQL() doesn't URL encode cqlStatementOperator
and operatorBetweenArgs. This may result in CQL injection.
Solution:
URL encode the complete CQL query.

RMB-803: Fix URL encoding in BuildCQL preventing CQL injection

---

pom.xml

Update Netty version, fixing
Local Information Disclosure Vulnerability in Netty on Unix-Like systems due temporary files.
https://nvd.nist.gov/vuln/detail/CVE-2021-21290
https://github.com/netty/netty/security/advisories/GHSA-5mcr-gq6c-3hq2

Netty 4.1.59.Final (CVE-2021-21290)

---

domain-models-api-interfaces/ramls/sample.raml
domain-models-runtime/pom.xml
domain-models-runtime/src/main/java/org/folio/rest/RestRouting.java
domain-models-runtime/src/main/java/org/folio/rest/RestVerticle.java
domain-models-runtime/src/test/java/org/folio/DemoRamlRestTest.java
domain-models-runtime/src/test/java/org/folio/rest/RestRoutingTest.java
domain-models-runtime/src/test/java/org/folio/rest/RestVerticleTest.java
domain-models-runtime/src/test/java/org/folio/rest/client/RmbtestsClientTest.java
domain-models-runtime/src/test/java/org/folio/rest/impl/BooksDemoAPI.java

Big refactor; all user requests handled in static class RestRouting.
Use Vert.x route for each of the routes offered, instead of
one big fat route function that does everything (slow and big).
This has been tested with mod-inventory-storage and all tests pass.
RMB returns 404 on path/method not found (actually this is thrown by Vert.x
itself now that only supported routes are registered).

RestVerticle checks for implementation at startup RMB-805

---

domain-models-runtime/pom.xml

de.flapdoodle.embed.process:2.0.5 dependes on vulnerable
org.apache.commons:commons-compress:1.10 that allows a
Denial of Service (DoS) attack when reading a
specially crafted ZIP archive.
Flapdoodle 2.1.2 depends on the fixed Commons-compress 1.18.
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-11771
https://app.snyk.io/vuln/SNYK-JAVA-ORGAPACHECOMMONS-32473

Flapdoodle 2.1.2, Commons-compress 1.18, fixing ReDoS

---

PERSONAL_DATA_DISCLOSURE.md

Please see https://issues.folio.org/browse/RMB-770 
Note: below would mean any RMB based modules will need to check both `userId` and `IP` in the form.
- RMB uses okapi-common logging to log `userId`
- `IP` is used in https://github.com/folio-org/raml-module-builder/blob/master/domain-models-runtime/src/main/java/org/folio/rest/tools/utils/LogUtil.java#L25 and https://github.com/folio-org/raml-module-builder/blob/master/domain-models-runtime/src/main/java/org/folio/rest/tools/utils/LogUtil.java#L35

RMB-770 Add PERSONAL_DATA_DISCLOSURE form

---

domain-models-runtime/src/main/java/org/folio/rest/persist/PostgresClientStreamResult.java

PostgresClient.streamGet methods have this reply parameter:
Handler<AsyncResult<PostgresClientStreamResult<T>>> replyHandler
This can only been used from all packages if the visibility of PostgresClientStreamResult is changed from package-private to public.

RMB-812: Make PostgresClientStreamResult public

---

domain-models-runtime/src/main/java/org/folio/rest/persist/Conn.java
domain-models-runtime/src/main/java/org/folio/rest/persist/PostgresClient.java
domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientIT.java

Futurised methods return a Future<RowSet<Row>>.
A List<RowSet<Row>> is not needed because a
RowSet<Row> is an Iterable<Row>.
To avoid a breaking change existing methods with a
`Handler<AsyncResult<List<RowSet<Row>>>> replyHandler`
parameter are not changed.

RMB-819: Atomic batch PostgresClient.execute with List<Tuple>

---

Jenkinsfile

The doApiLint facility replaces runLintRamlCop
https://dev.folio.org/guides/api-lint/

FOLIO-2893 Use api-lint CI facility

---

Jenkinsfile

The doApiDoc facility replaces publishAPI
https://dev.folio.org/guides/api-doc/

FOLIO-2898 Use api-doc CI facility

---

cql2pgjson/src/main/java/org/folio/cql2pgjson/CQL2PgJSON.java
cql2pgjson/src/test/java/org/folio/cql2pgjson/CQL2PgJSONTest.java
cql2pgjson/src/test/resources/templates/db_scripts/schema.json

Also search a table name in the auditingTableName field
and suppress a "Table ... NOT FOUND" warning if found to
be an auditing table.

RMB-829: Suppress "Table audit_... NOT FOUND" in loadDbSchema()

---

README.md
doc/upgrading.md
domain-models-maven-plugin/src/main/java/org/folio/rest/tools/ClientGenerator.java
domain-models-maven-plugin/src/main/java/org/folio/rest/tools/DomainModelsMojo.java
domain-models-maven-plugin/src/main/java/org/folio/rest/tools/GenerateRunner.java
domain-models-maven-plugin/src/test/java/org/folio/rest/tools/ClientGeneratorTest.java

This is a clarification for client generated code, not a fix.
For earlier versions client code also required depending the artifact with generated classes.. Since the client generator is using annotations as "input" (not RAML).
But also a bug fix for finding base path of RAML source (seen with mod-configuration).

raml plugin no generated clients RMB-831

---

README.md
domain-models-runtime/src/main/java/org/folio/rest/persist/Conn.java
domain-models-runtime/src/main/java/org/folio/rest/persist/PostgresClient.java
domain-models-runtime/src/main/java/org/folio/rest/persist/ddlgen/SchemaMaker.java
domain-models-runtime/src/main/resources/templates/db_scripts/general_functions.ftl
domain-models-runtime/src/test/java/org/folio/rest/jaxrs/model/User.java
domain-models-runtime/src/test/java/org/folio/rest/persist/ConnIT.java
domain-models-runtime/src/test/java/org/folio/rest/persist/GeneralFunctionsIT.java
domain-models-runtime/src/test/java/org/folio/rest/persist/LoadGeneralFunctions.java
domain-models-runtime/src/test/java/org/folio/rest/persist/PgUtilIT.java
domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientIT.java
domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientTest.java
domain-models-runtime/src/test/java/org/folio/rest/persist/ddlgen/SchemaMakerTest.java

Upsert using INSERT ... ON CONFLICT (id) DO UPDATE fails because the INSERT
trigger overwrites the _version property that the UPDATE trigger uses to
detect optimistic locking conflicts.
Solution:
Implement upsert using a transaction and executing two SQL commands:
UPDATE ...;
IF NOT FOUND THEN INSERT ...;
Adding updateBatch allows to replace upsertBatch depending on the use case:
insertBatch or updateBatch. When optimistic locking is enabled the client
must know in advance whether it is insert or update.

RMB-832: Implement upsert, updateBatch for optimistic locking

---

domain-models-runtime/src/main/java/org/folio/rest/persist/Conn.java
domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientIT.java

PostgreSQL log:
```
ERROR:  could not determine polymorphic type because input has type unknown
STATEMENT:  SELECT upsert('foo', $1, $2)
ERROR:  current transaction is aborted, commands ignored until end of transaction block
```

RMB-841: upsertBatch with transaction (connection) fails

---

pom.xml

Eclipse Jersey 2.28 to 2.33 contains a local information disclosure vulnerability
due to the use of the File.createTempFile.
Version 2.34 has a fix.

Bump jersey-media-json-jackson from 2.29.1 to 2.34 (CVE-2021-28168)

---

domain-models-runtime/src/main/java/org/folio/rest/impl/TenantAPI.java

If a POST tenant fails TenantAPI should report the failure by setting the job error.
However, if the failure message is null the job error is set to null, this indicates no error.
Approach:
If failure message is null report the exception class name.

RMB-844: Properly report POST tenant with null exception message

---

domain-models-maven-plugin/src/main/java/org/folio/rest/tools/ClientGenerator.java
domain-models-maven-plugin/src/test/resources/clients/TestClient.txt
domain-models-runtime/src/main/java/org/folio/rest/tools/client/BuildCQL.java
domain-models-runtime/src/main/java/org/folio/rest/tools/utils/TenantLoading.java
domain-models-runtime/src/test/java/org/folio/rest/tools/utils/BuildCQLTest.java
util/src/main/java/org/folio/util/PercentCodec.java
util/src/main/java/org/folio/util/StringUtil.java
util/src/test/java/org/folio/util/PercentCodecTest.java

RFC 3986 mandates that only percent encoding is used for
HTTP requests. Using a plus to encode a space is wrong:
https://datatracker.ietf.org/doc/html/rfc3986
Wrong encoding of status == open:
`?query=status+%3D%3D+open`
Correct encoding of status == open:
`?query=status%20%3D%3D%20open`
Approach:
Implement PercentCodec.
Put a warning into the StringUtil.urlEncode javadoc.
Replace StringUtil.urlEncode calls by PercentCodec calls.

RMB-843: Use percent encoding, not url encoding, for HTTP requests

---

doc/upgrading.md
domain-models-runtime/src/main/java/org/folio/rest/persist/PostgresClient.java
domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientTest.java

Add javadoc and a unit test to ensure that PostgresTester is always closed, even when the same PostgresTester instance is used twice in sequence.

RMB-848: Always close PostgresTester

---

doc/upgrading.md
domain-models-maven-plugin/src/main/java/org/folio/rest/tools/ModuleNameWriter.java
domain-models-runtime-it/src/test/java/org/folio/rest/ModuleNameTest.java

RMB 33.0.0 removed PomReader.INSTANCE.getVersion().
Some RMB based modules need this, for example
MODPUBSUB-179 = https://github.com/folio-org/mod-pubsub/pull/160
Solution:
Provide ModuleName.getModuleVersion() that returns the same value as PomReader.INSTANCE.getVersion() did before.

RMB-853: ModuleName.getModuleVersion()

---

domain-models-runtime/src/main/java/org/folio/rest/RestVerticle.java

Some tenants exceed the current limit of 16384.
Solution: Double the limit.

RMB-854: Increase FORM_ATTRIBUTE_SIZE_MAX from 16384 to 32768

---

domain-models-api-interfaces/pom.xml
domain-models-maven-plugin/src/main/java/org/folio/rest/tools/ModuleNameWriter.java
domain-models-runtime/src/main/java/org/folio/rest/persist/PostgresClient.java
domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientTest.java
domain-models-runtime/src/test/java/org/folio/rest/tools/utils/ModuleName.java

domain-models-api-interfaces (and domain-models-runtime
that depends on it) ships with a ModuleName class with
getModuleName() returning "raml_module_builder".
An RMB based module creates a correct ModuleName class
when running domain-models-maven-plugin.
If we are lucky the latter is included in the final jar.
For mod-feesfines I sometimes have integration tests failure
because of wrong order resulting in the
wrong "raml_module_builder" where it should be "mod_feesfines".
Removing ModuleName class from domain-models-api-interfaces jar
resolves this issue; it requires reflection to load
ModuleName class, though.

RMB-849: Remove ModuleName class from domain-models-api-interfaces

---

domain-models-runtime/src/main/java/org/folio/rest/RestVerticle.java
domain-models-runtime/src/main/java/org/folio/rest/tools/client/HttpClientFactory.java

Building or releasing mod-user-import master fails when run locally from the shell.
The unit tests succeed when run from IDE and on Jenkins.
Cause is a race condition:
https://github.com/folio-org/raml-module-builder/blob/v33.0.1/domain-models-runtime/src/main/java/org/folio/rest/RestVerticle.java#L114-L119
https://github.com/folio-org/raml-module-builder/blob/v33.0.1/domain-models-runtime/src/main/java/org/folio/rest/tools/client/HttpClientFactory.java#L17-L21
Mocking can be enabled by setting a Verticle DeploymentOption.
RestVerticle reads it and passes this information to
HttpClientFactory by setting a system property.
HttpClientFactory checks the system property when the class
loader loads the HttpClientFactory class, this might be
before RestVerticle sets the system property (race …

RMB-858: HttpClientMock2 not enabled due to race condition

---

domain-models-api-interfaces/pom.xml
domain-models-runtime/pom.xml

RMB ships with xerces:xmlParserAPIs:2.6.2.
This library has been included into JDK since Java 9.
Using any of these classes (org.w3c.dom.**) causes this
compile error in some Java compilers (for example the one used by Eclipse):
`The package org.w3c.dom is accessible from more than one module: <unnamed>, java.xml`
Solution:
Remove this dependency.

RMB-859: Remove xerces:xmlParserAPIs dependency

---

cql2pgjson/src/main/java/org/folio/cql2pgjson/util/DbSchemaUtils.java
cql2pgjson/src/test/java/org/folio/cql2pgjson/DeletedIndexTest.java
cql2pgjson/src/test/resources/templates/db_scripts/schemaWithDeletedIndex.json

RMB (CQL2PgJSON, DbSchemaUtils) uses an index that has been deleted and has tOps been set to DELETE.

RMB-864: Ignore deleted index in schema.json

---

doc/upgrading.md
domain-models-runtime/src/test/java/org/folio/rest/persist/PgPoolBase.java
domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientIT.java
domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientTransactionsIT.java
pom.xml

Most notable fix is the "prepared statement ... already exists" issue:
https://github.com/eclipse-vertx/vertx-sql-client/pull/737
The Vertx team has merged our fix upstream therefore we no longer need
to use our fork https://github.com/folio-org/vertx-sql-client
Vert.x 4.1.2 adds three new methods to PgPool. Instead of adding
them to our multiple PgPool mocks the duplicated methods are
extracted into PgPoolBase.

RMB-862: Upgrade Vert.x from 4.1.0 to 4.1.2

---

domain-models-runtime/src/main/java/org/folio/rest/persist/PgUtil.java
domain-models-runtime/src/test/java/org/folio/rest/persist/PgUtilIT.java

Add unit tests for invalid CQL that checks that 400 is returned.
No code change to PgUtil because it already returns 400 on invalid CQL:
* get
* getWithOptimizedSql
* streamGet
* delete
However, this pull request makes a PgUtil code change to fix the HTTP status on invalid table name that
should return 500 but has returned 400.

RMB-865: Ensure that PgUtil returns 400 (not 500) on invalid CQL

---

domain-models-runtime/src/main/java/org/folio/rest/RestRouting.java
domain-models-runtime/src/test/java/org/folio/rest/RestRoutingTest.java

Fix JSON made by javax.validation:
* Properly handle read-only sub-fields
* Use translation key as javax.validation translates the message

RMB-538: JSON validation: read-only sub-fields, translation code

---

domain-models-runtime/src/main/java/org/folio/rest/persist/Criteria/Criteria.java
domain-models-runtime/src/main/java/org/folio/rest/persist/facets/FacetField.java
domain-models-runtime/src/main/java/org/folio/rest/tools/client/HTTPJsonResponseHandler.java

As per my understanding,  Line:-117 & 125  "field.get(0).replaceAll("^'|'$", "")" is used for removing single quotes from the field. That can be done with "field.get(0).replace("'", "")" also.

"replaceAll" modified to replace in Criteria.class

---

doc/upgrading.md
pom.xml

Running a module with RMB 33.1.0 and Vert.x >= 4.1.3 causes this failure at runtime:
java.lang.NoSuchMethodError: 'java.lang.Object io.vertx.core.Context.getLocal(java.lang.String)'
at org.folio.okapi.common.logging.FolioLoggingContext.lookup(FolioLoggingContext.java:62)
Vert.x <= 4.1.2 uses Context.getLocal(String).
Vert.x >= 4.1.3 uses Context.getLocal(Object).
https://github.com/eclipse-vertx/vert.x/commit/4d408d28d764d1eac65dccefa1578251f0060e5f
okapi-common < 4.9.0 uses Vert.x <= 4.1.2 yielding Context.getLocal(String).
okapi-common >= 4.9.0 uses Vert.x >= 4.1.3 yielding Context.getLocal(Object).
https://github.com/folio-org/okapi/commit/625c85021d0689fdc3872048a4b7249efc5c771b

RMB-874: Update Vert.x to 4.1.4 and okapi-common to 4.9.0

---

README.md
domain-models-runtime/src/main/java/org/folio/rest/persist/PostgresClient.java
domain-models-runtime/src/main/java/org/folio/rest/tools/utils/Envs.java
domain-models-runtime/src/test/java/org/folio/DemoRamlRestTest.java
domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientIT.java

DB_MAXSHAREDPOOLSIZE uses "SET ROLE ..." to switch to a tenant specific database role with restricted permission.
Vert.x prints a warning "Parameter is_superuser changed to off" or "Parameter is_superuser changed to on" since 4.1.0: https://github.com/eclipse-vertx/vertx-sql-client/commit/0bd1571d033ba35f57d188472c902b81b35dbd11
This should be changed in Vert.x: https://github.com/eclipse-vertx/vertx-sql-client/pull/1060

RMB-664: One connection pool for all tenants

---

domain-models-runtime/src/test/java/org/folio/rest/persist/PgPoolBase.java
domain-models-runtime/src/test/java/org/folio/rest/persist/PgUtilIT.java
domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientIT.java
domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientTest.java
domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientTransactionsIT.java
pom.xml

mod-inventory-storage successfully builds with this RMB commit after adopting some test asserts to the new SQL error string of Vert.x 4.2.0: https://github.com/eclipse-vertx/vertx-sql-client/commit/6fa1180ad8c3d8683716d0de3b81ecdac394ca3f

RMB-880: Update Vert.x from 4.1.4 to 4.2.1

---

pom.xml

https://nvd.nist.gov/vuln/detail/CVE-2021-45105
https://logging.apache.org/log4j/2.x/security.html

RMB-891: Log4j 2.17.0 fixing self-referential lookups in MDC

---

pom.xml

Vert.x 4.2.2 comes with Netty 4.1.72.Final that fixes a header request smuggling vulnerability:
https://nvd.nist.gov/vuln/detail/CVE-2021-43197

RMB-892: Vert.x 4.2.2, Netty 4.1.72 fixing CVE-2021-43197

---

cql2pgjson-cli/pom.xml
cql2pgjson/pom.xml
domain-models-api-aspects/pom.xml
domain-models-runtime/pom.xml
domain-models-runtime/src/test/java/org/folio/DemoRamlRestTest.java
pom.xml

Update Vert.x from 4.2.2 to 4.2.3
Update log4j from 2.17.0 to 2.17.1
Update hibernate-validator from 6.1.7.Final to 6.2.1.Final
Update commons-cli from 1.4 to 1.5.0
Update commons-lang3 from 3.8.1 to 3.12.0
Update okapi-common from 4.9.0 to 4.12.0
Update JUnitParams from 1.1.0 to 1.1.1
Update postgresql from 42.2.14 to 42.3.1
Update maven-resources-plugin from 3.1.0 to 3.2.0
Update versions-maven-plugin from 2.7 to 2.8.1
Update maven-checkstyle-plugin from 3.1.1 to 3.1.2
Update maven-release-plugin from 3.0.0-M1 to 3.0.0-M4
Update maven-javadoc-plugin from 3.2.0 to 3.3.1
Update maven-deploy-plugin from 3.0.0-M1 to 3.0.0-M2
Remove unused javax.mail:mailapi dependency.

RMB-893: Bump dependencies: Vert.x 4.2.3, log4j 2.17.1, etc.

---

domain-models-api-aspects/pom.xml
domain-models-api-interfaces/pom.xml
domain-models-runtime-it/ramls/bee.json
domain-models-runtime-it/src/test/java/org/folio/rest/BeesApiTest.java
domain-models-runtime/pom.xml
pom.xml

Duplicate dependencies – the same class provided by multiple declared dependencies – result in non-deterministic builds because maven picks one of them.
Remove javax.el:javax.el-api, it is already provided by org.glassfish:javax.el
Exclude jakarta.ws.rs-api, we already have javax.ws.rs-api
Exclude javax.activation:activation, we already have jakarta.activation-api
Exclude jakarta.validation-api, we already have javax.validation:validation-api
Add unit test with minimum constraint in bee.json to ensure that it still works.

RMB-894: Exclude duplicate dependencies

---

domain-models-runtime/src/main/java/org/folio/rest/persist/PostgresClient.java

Needed when constructing SQL for PostgresClient.execute.

Make PostgresClient.getSchemaName() public

---

domain-models-runtime/src/main/java/org/folio/rest/RestRouting.java

Example with incorrect stipping:
`{"errors":[{"message":"elements in list must match pattern","type":"1","code":"lements in list must match patter","parameters":[{"key":"statisticalCodeIds","value":"[foo]"}]}]}`

Don't strip enclosing {} if there are no

---

cql2pgjson/pom.xml

This is only used in testing.
See https://github.com/advisories/GHSA-v7wg-cpwc-24m4

Upgrade org.postgresql:postgresql

---

cql2pgjson/pom.xml

This fixes an arbitrary file write vulnerability:
https://github.com/pgjdbc/pgjdbc/commit/f6d47034a4ce292e1a659fa00963f6f713117064
https://github.com/advisories/GHSA-673j-qm5f-xpv8
This JDBC driver is used by unit tests of cql2pgjson and
they are not affected, but updating resolves false positive
warnings by security scanners like GitHub dependabot.

Bump postgresql from 42.3.2 to 42.3.3

---

domain-models-api-aspects/pom.xml
domain-models-maven-plugin/pom.xml
pom.xml

Update Vert.x from 4.2.3 to 4.2.5. This updates indirect dependencies
like Netty from 4.1.73.Final to 4.1.74.Final.
https://github.com/vert-x3/wiki/wiki/4.2.5-Release-Notes
Update javassist from 3.27.0-GA to 3.28.0-GA.
Update maven-plugin-annotations from 3.6.0 to 3.6.4.
Update hibernate-validator from 6.2.1.Final to 6.2.2.Final.

RMB-898: Update Vertx (to 4.2.5) and other dependencies

---

domain-models-runtime/src/main/java/org/folio/rest/tools/utils/NetworkUtils.java

These methods are not used:
* object2Bytes - https://github.com/search?q=org%3Afolio-org+object2Bytes&type=code https://github.com/search?q=org%3Aopenlibraryenvironment+object2Bytes&type=code
* readURL - https://github.com/search?q=org%3Afolio-org+readURL&type=code https://github.com/search?q=org%3Aopenlibraryenvironment+readURL&type=code
* isValidURL - https://github.com/search?q=org%3Afolio-org+isValidURL&type=code https://github.com/search?q=org%3Aopenlibraryenvironment+isValidURL&type=code
They have no unit test coverage.
Sonar reports 4 code smells in them: https://sonarcloud.io/code?id=org.folio%3Araml-module-builder&selected=org.folio%3Araml-module-builder%3Adomain-models-runtime%2Fsrc%2Fmain%2Fjava%2Forg%2Ffolio%2Frest%2Ftools%2Futils%2FNetworkUtils.java
These 3 methods should be …

RMB-904: Remove unused object2Bytes, readURL, isValidURL in NetworkUtils

---

README.md
domain-models-runtime/src/main/java/org/folio/rest/persist/PostgresClient.java
domain-models-runtime/src/main/java/org/folio/rest/tools/utils/Envs.java
domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientTest.java
domain-models-runtime/src/test/java/org/folio/rest/tools/utils/EnvsTest.java

https://issues.folio.org/browse/RMB-901
DB timeout issues happen most often when the system is not warmed up and
connection pool does not contain any open connections.

RMB-901: reconnectAttempts and reconnectInterval for PgConnectOptions

---

cql2pgjson/pom.xml
dbschema/pom.xml
domain-models-runtime-it/src/test/java/org/folio/rest/ApiTestBase.java
domain-models-runtime/pom.xml
domain-models-runtime/src/main/resources/templates/db_scripts/metadata.ftl
domain-models-runtime/src/test/java/org/folio/rest/impl/TenantAPIIT.java
postgres-testing/pom.xml
util/pom.xml

Existing metadata date format:
```
"metadata": {
"createdDate": "2020-10-19T09:31:31.529",
"updatedDate": "2020-10-19T09:31:31.529+00:00",
"createdByUserId": "ba6baf95-bf14-4020-b44c-0cad269fb5c9",
"updatedByUserId": "ba6baf95-bf14-4020-b44c-0cad269fb5c9"
}
```
Always having a time zone string prevents software running in an
environment with some time offset from incorrectly interpreting
the time as local time.
New metadata date format:
"metadata": {
"createdDate": "2020-10-19T09:31:31.529Z",
"updatedDate": "2020-10-19T09:31:31.529Z",
"createdByUserId": "ba6baf95-bf14-4020-b44c-0cad269fb5c9",
"updatedByUserId": "ba6baf95-bf14-4020-b44c-0cad269fb5c9"
}
No migration needed, for details see
https://issues.folio.org/browse/RMB-759

RMB-759: Use Z time zone for createdDate and updatedDate metadata

---

pom.xml

Update jackson-databind from 2.13.1 to 2.13.2.1 fixing https://nvd.nist.gov/vuln/detail/CVE-2020-36518
Update Vert.x from 4.2.5 to 4.2.6.
Update log4j from 2.17.1 to 2.17.2.

RMB-907: jackson-databind 2.13.2.1, Vert.x, log4j (CVE-2020-36518)

---

pom.xml

The first entry takes precendence over later entries in pom.xml.
This test shows that it is correct now:
mvn dependency:tree -Dincludes=com.fasterxml.jackson.core:jackson-databind

RMB-907: Move jackson-databind entry before jackson-bom

---

domain-models-runtime/src/main/resources/templates/db_scripts/optimistic_locking.ftl
domain-models-runtime/src/test/java/org/folio/rest/persist/ddlgen/SchemaMakerIT.java
domain-models-runtime/src/test/resources/templates/db_scripts/schemaWithOptimisticLocking3.json

PostgreSQL allows up to 1000 digits for the _version number: https://www.postgresql.org/docs/current/datatype-numeric.html#DATATYPE-NUMERIC-DECIMAL
JSON has no number restriction: https://www.json.org/json-en.html
RAML also has no restrictions for the number and integer types: https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#number
mod-inventory-storage declares _version to be of RAML type integer: https://github.com/folio-org/mod-inventory-storage/blob/v23.0.2/ramls/instance.json#L11
RMB incorrectly generates Java type Integer in org.folio.rest.jaxrs.model.Instance.java.
This will result in a parse exception when Integer.MAX_VALUE = 2147483647 is exceeded.
It takes 68 years when incrementing each second. It takes only 1 year when incrementing 68 times per …

RMB-911: Optimistic locking _version overflow

---

pom.xml

Move jackson entry before vertx entry like it is on master.
Otherwise jackson version provided by vertx overwrites the
patched version.

RMB-907: b33.2 jackson-databind 2.13.2.1

---

domain-models-runtime/src/main/java/org/folio/rest/impl/TenantAPI.java
domain-models-runtime/src/test/java/org/folio/rest/impl/TenantAPIIT.java

As a sysop, devop or developer I want a good error message if the PostgreSQL server version is too old.
Currently I get an error message like this:
```
Tenant operation failed for module mod-inventory-storage-23.0.2: SQL error
CREATE TRIGGER check_statistical_code_references_on_insert BEFORE INSERT ON
item FOR EACH ROW WHEN (NEW.jsonb->'statisticalCodeIds' IS NOT NULL AND
NEW.jsonb->'statisticalCodeIds' <> '[]') EXECUTE FUNCTION
check_statistical_code_references();ERROR: 42601: syntax error at or near "FUNCTION"
```
This doesn't give any indication what the root cause is.
Solution: On POST /_/tenant check the server version and fail if no longer supported.

RMB-913: Fail if PostgreSQL version is too old

---

domain-models-runtime/src/main/java/org/folio/rest/persist/PostgresClient.java

Make PostgresClient#getTenantId() public. This may help a module because the tenantId no longer needs to be passed separately.

RMB-915: public PostgresClient#getTenantId()

---

domain-models-api-aspects/pom.xml
pom.xml

Bump org.glassfish:javax.el:3.0.1-b12 to org.glassfish:jakarta.el:3.0.4 fixing a bug in the Jakarta Expression Language implementation that enables invalid EL expressions to be evaluated as if they were valid: https://nvd.nist.gov/vuln/detail/CVE-2021-28170
Note that the artifact has been renamed from javax.el to jakarta.el: https://mvnrepository.com/artifact/org.glassfish/javax.el

RMB-918: Fix Jakarta Expression Language validation (CVE-2021-28170)

---

domain-models-runtime/src/main/java/org/folio/rest/persist/PgUtil.java
domain-models-runtime/src/test/java/org/folio/rest/persist/PgUtilIT.java

As a sysop or librarian using the DELETE by CQL API I might accidentally omit the query parameter or mistype it: quer=username==foo
How to reproduce:
Call PgUtil.delete by CQL with CQL query parameter that is null (= missing), empty or whitespace only.
Expected Results:
PgUtil.delete by CQL rejects the API call with a 400 HTTP status code and doesn't delete anything.
Actual Results:
PgUtil.delete deletes all records.
Additional Information:
This bug has already caused severe issues: https://issues.folio.org/browse/MODINVSTOR-901

RMB-919: Delete by CQL rejects missing or empty CQL

---

doc/upgrading.md
domain-models-runtime/src/main/java/org/folio/rest/tools/utils/TenantTool.java

mod-inventory-storage has several unit tests that pass a Map.of() and fail when upgrading to RMB 34:
https://github.com/folio-org/mod-inventory-storage/blob/v23.0.3/src/test/java/org/folio/rest/api/AsyncMigrationTest.java#L142
https://github.com/folio-org/mod-inventory-storage/blob/v23.0.3/src/test/java/org/folio/rest/api/IterationJobRunnerTest.java#L134
https://github.com/folio-org/mod-inventory-storage/blob/v23.0.3/src/test/java/org/folio/rest/api/NotificationSendingErrorRepositoryTest.java#L35
https://github.com/folio-org/mod-inventory-storage/blob/v23.0.3/src/test/java/org/folio/rest/api/ReindexJobRunnerTest.java#L185

RMB-922: Migrate to case insensitive x-okapi-tenant header

---

domain-models-runtime/pom.xml

Use JDK 17 and run mvn clean install.
It fails with this error:
```
[ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:4.0.1:revision
(get-the-git-infos) on project domain-models-runtime: Could not complete Mojo execution...:
Unable to make
private void java.util.Properties.store0(java.io.BufferedWriter,java.lang.String,boolean) throws java.io.IOException
accessible: module java.base does not "opens java.util" to unnamed module
@79e8a26c -> [Help 1]
```
This is fixed by upgrading pl.project13.maven:git-commit-id-plugin:4.0.1 to version 5.0.0: https://github.com/git-commit-id/git-commit-id-maven-plugin/releases/tag/v5.0.0

RMB-930: Upgrade git-commit-id-plugin for JDK 17

---

domain-models-runtime/src/main/java/org/folio/rest/persist/Conn.java
domain-models-runtime/src/main/java/org/folio/rest/persist/PostgresClient.java
domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientIT.java

Implemented additional Read methods that handle exclusive reads while undo changes to some existing read methods that can be used in writing to the database as well. This work is done to address the comments raised by @julianladisch in https://github.com/folio-org/raml-module-builder/pull/1047.  (The 1047 PR is still open but the new commits don't seem to be recognized by Github in this PR to show the differences, thus this new PR is created.)

RMB-348 (Cont.)

---

domain-models-runtime/src/main/java/org/folio/rest/persist/PostgresClient.java

This method is useless and misleading because it always uses the provided
SQLConnection and cannot change whether the SQLConnection is
read-write or read-only.
withConn(AsyncResult<SQLConnection>, Function) should be used instead.

RMB-348: Remove withReadConn(AsyncResult<SQLConnection>, Function)

---

domain-models-runtime/src/test/java/org/folio/rest/persist/PgConnectionMock.java
domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientIT.java
domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientTest.java
domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientTransactionsIT.java
pom.xml

Vert.x 4.3.0 and 4.3.1 have this regression: They disable SSL in WebClient.
Vert.x >= 4.3.2 has a fix.
https://github.com/vert-x3/vertx-web/issues/2196 "SSL not set for secure Request"
https://github.com/vert-x3/vertx-web/pull/2226 "WebClient ignores the SSL flag when a request is created from request options with the SSL flag true"
https://github.com/vert-x3/vertx-web/issues/2225 "HttpRequestImpl's SSL Isn't Set By RequestOptions"

RMB-934: Vert.x 4.3.3 fixing disabled SSL in 4.3.0/4.3.1

---

domain-models-runtime/src/main/java/org/folio/rest/impl/TenantAPI.java
domain-models-runtime/src/test/java/org/folio/rest/impl/TenantAPIIT.java

Use the stored moduleVersion as previous version rather than module_from from tenant init call. The module_from does not always reflect the true state of module data.

Fix previous version used for migration scripts RMB-937

---

README.md
dbschema/src/main/java/org/folio/dbschema/OptimisticLockingMode.java
domain-models-runtime/src/main/java/org/folio/rest/persist/PgUtil.java
domain-models-runtime/src/main/java/org/folio/rest/tools/utils/OptimisticLockingUtil.java
domain-models-runtime/src/main/resources/templates/db_scripts/optimistic_locking.ftl
domain-models-runtime/src/test/java/org/folio/rest/persist/ddlgen/SchemaMakerIT.java
domain-models-runtime/src/test/java/org/folio/rest/tools/utils/OptimisticLockingUtilTest.java
domain-models-runtime/src/test/resources/templates/db_scripts/schemaWithOptimisticLocking.json
domain-models-runtime/src/test/resources/templates/db_scripts/schemaWithOptimisticLocking2.json
domain-models-runtime/src/test/resources/templates/db_scripts/schemaWithOptimisticLocking3.json

* Add environment variable DB_ALLOW_SUPPRESS_OPTIMISTIC_LOCKING
* Add schema configuration "withOptimisticLocking": "failOnConflictUnlessSuppressed"
* Add OptimisticLockingUtil with helper methods
* Add PgUtil.postSyncUnsafe
* Handle "_version": -1 in PgUtil.put and PgUtil.postSync
For details see https://issues.folio.org/browse/MODINVSTOR-924

RMB-939: failOnConflictUnlessSuppressed for optimistic locking

---

NEWS.md
cql2pgjson-cli/pom.xml
cql2pgjson/pom.xml
dbschema/pom.xml
domain-models-api-aspects/pom.xml
domain-models-api-interfaces/pom.xml
domain-models-maven-plugin/pom.xml
domain-models-runtime-it/pom.xml
domain-models-runtime/pom.xml
domain-models-runtime/src/main/java/org/folio/rest/persist/helpers/LocalColumnDescriptor.java
domain-models-runtime/src/main/java/org/folio/rest/persist/helpers/LocalRowDesc.java
domain-models-runtime/src/main/java/org/folio/rest/persist/helpers/LocalRowSet.java
domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientIT.java
domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientTest.java
pom.xml
postgres-testing/pom.xml
testing/pom.xml
util/pom.xml

RMB <= 35.0.0 used with Vert.x >= 4.3.4 fails with this error:
`java.lang.NoSuchMethodError: 'void io.vertx.sqlclient.impl.RowDesc.<init>(io.vertx.sqlclient.desc.ColumnDescriptor[])'`
RMB >= 35.0.1 used with Vert.x <= 4.3.3 fails with this error:
`java.lang.NoSuchMethodError: 'void io.vertx.sqlclient.impl.RowDesc.<init>(java.util.List, java.util.List)'`

Release 35.0.1

---

domain-models-runtime/src/main/java/org/folio/rest/persist/PostgresClient.java
domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientIT.java

Trying to get a database connection may time out, for example with unknown host name on AWS ec2 because the DNS doesn't immediately return a failure but takes long time.
vertx-pg-client returns a NoStackTraceThrowable with this message: Timeout
This error message should indicate that it is database related and which hostname has been used, for example: Timeout for DB_HOST:DB_PORT=pg.example.com:5432

RMB-949: Report PostgreSQL URI on timeout

---

pom.xml

Upgrade jackson-databind from 2.13.4 to 2.13.4.2 fixing Denial of Service (DoS):
https://nvd.nist.gov/vuln/detail/CVE-2022-42003

RMB-948: jackson-databind 2.13.4.2 fixing DoS CVE-2022-42003

---

.github/workflows/api-doc.yml
.github/workflows/api-lint.yml
.github/workflows/api-schema-lint.yml
Jenkinsfile
domain-models-api-interfaces/ramls/admin.raml

[FOLIO-3678](https://issues.folio.org/browse/FOLIO-3678)
Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-schema-lint](https://dev.folio.org/guides/describe-schema/) and [api-doc](https://dev.folio.org/guides/api-doc/)
(instead of Jenkins-operated CI stages).

FOLIO-3678 RMB-964 Use GitHub Workflows api-lint and api-schema-lint and api-doc

---

domain-models-runtime/src/main/resources/templates/db_scripts/create.ftl

While looking at https://issues.folio.org/browse/CIRCSTORE-377, noticed that db `search_path` for `tenant_module` user is not set up correctly. This PR fixes that.

Set correct db search_path for tenant_module user

---

README.md
domain-models-runtime/src/main/java/org/folio/rest/persist/PostgresClient.java
domain-models-runtime/src/main/java/org/folio/rest/persist/PostgresClientInitializer.java
domain-models-runtime/src/main/java/org/folio/rest/persist/PostgresClientWithAsyncReadConn.java
domain-models-runtime/src/main/java/org/folio/rest/persist/cache/CachedConnectionManager.java
domain-models-runtime/src/main/java/org/folio/rest/tools/utils/Envs.java
domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientIT.java
domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientTest.java
domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientWithAsyncReadConnTest.java

https://folio-org.atlassian.net/browse/RMB-975
Breaks logic for constructing the three types of hosts out into its own class since it is now used by `PostgresClient` and `PostgresClientWithAsyncReadConn`. `PostgresClientWithAsyncReadConn` is responsible for setting the read host to be the async reader. Users can use the `PostgresClient` returned from PostgresClientWithAsyncReadConn.getInstance` as a drop in replacement of `PostgresClient`.
I opted to use inheritance rather than composition to make `PostgresClientWithAsyncReadConn` since extending it didn't require wrapping of all of the `SELECT` type of methods. If there are certain methods we don't want to support, it is easy enough to add overrides and throw an unsupported operation exception if needed.

RMB-975: Define  DB_HOST_ASYNC_READER, DB_PORT_ASYNC_READER 
