domain-models-runtime/pom.xml, domain-models-runtime/src/main/java/org/folio/rest/persist/PostgresClient.java, domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientTest.java, pom.xml
fix closeClient(...) when client==null
handle DEFAULT_SCHEMA
add unit tests
=> DMOD-165 close client

domain-models-api-aspects/pom.xml, domain-models-api-interfaces/pom.xml, domain-models-interface-extensions/pom.xml, domain-models-runtime/pom.xml, domain-models-runtime/src/main/java/org/folio/rest/persist/cql/CQLWrapper.java, domain-models-runtime/src/test/java/org/folio/rest/persist/cql/CQLWrapperTest.java, pom.xml, postgres-runner/pom.xml, rules/pom.xml
constructor CQL2PgJSON(field) now throws a checked exception so we need a version bump
=> FOLIO-420 CQL2PgJSON new Exceptions, RMB version bump

domain-models-api-aspects/pom.xml, domain-models-api-interfaces/pom.xml, domain-models-interface-extensions/pom.xml, domain-models-runtime/pom.xml, domain-models-runtime/src/test/java/org/folio/rest/persist/cql/CQLWrapperTest.java, pom.xml, postgres-runner/pom.xml, rules/pom.xml
provided by cql2pgjson 1.0.1-SNAPSHOT
=> FOLIO-503 Support cql.allRecords=1

domain-models-api-aspects/pom.xml, domain-models-api-interfaces/pom.xml, domain-models-interface-extensions/pom.xml, domain-models-runtime/pom.xml, domain-models-runtime/src/main/java/org/folio/rest/persist/cql/CQLQueryValidationException.java, domain-models-runtime/src/main/java/org/folio/rest/persist/cql/CQLWrapper.java, domain-models-runtime/src/test/java/org/folio/rest/persist/cql/CQLWrapperTest.java, pom.xml, postgres-runner/pom.xml, rules/pom.xml
This is compatible because CQLQueryValidationException extends IllegalStateException
https://issues.folio.org/browse/DMOD-218
=> replace CQLWrapper's IllegalStateException by CQLQueryValidationException

domain-models-runtime/src/main/java/org/folio/rest/RestVerticle.java
Checkstyle reports three violations in red in https://jenkins-aws.indexdata.com/job/raml-module-builder-pull-request/org.folio$domain-models-runtime/51/console
This fixes them:
* remove class variable mappedURLs, it is used locally only
* reduce method length of start(Future<Void>) by extracting the main routing code into route(...); the IDE did the extraction, no other change has been made to route(...)
* replace empty catch block in sendResponse(...), fix Exception reporting
=> DMOD-169 remove checkstyle violations in RestVerticle

domain-models-api-aspects/pom.xml, domain-models-api-interfaces/pom.xml, domain-models-interface-extensions/pom.xml, domain-models-runtime/pom.xml, pom.xml, postgres-runner/pom.xml, rules/pom.xml
as requested on today's backend meeting
=> create non-SNAPSHOT version v10.0.7

domain-models-runtime/pom.xml, domain-models-runtime/src/main/java/org/folio/rest/persist/PostgresClient.java, postgres-runner/pom.xml
I checked the change and it works also under Ubuntu 14.04.5 LTS and openSUSE Leap 42.2.
=> RMB-25 embedded postgres 1.12 -> 2.2 to make it run on windows

codestyles.xml, domain-models-api-aspects/src/main/java/org/folio/JavassistPerfomanceInstrumenter.java, domain-models-interface-extensions/src/main/java/org/folio/rest/tools/GenerateRunner.java, domain-models-interface-extensions/src/main/java/org/folio/rest/tools/PomReader.java, domain-models-interface-extensions/src/main/java/org/folio/rest/tools/utils/Envs.java, domain-models-interface-extensions/src/test/java/org/folio/rest/tools/utils/EnvsTest.java, domain-models-runtime/pom.xml, pom.xml, postgres-runner/src/main/java/org/folio/rest/persist/PostgresRunner.java
I also fixed all checkstyle violations in the existing code.
=> RMB-10 checkstyle fails all modules on violation

README.md, domain-models-runtime/src/test/java/org/folio/rest/persist/ForeignKeyPerformanceIT.java, domain-models-runtime/src/test/resources/ForeignKeyPerformanceIT.sql, domain-models-runtime/src/test/resources/vertx-default-jul-logging.properties
Can be merged after https://issues.folio.org/browse/RMB-38 has been fixed.
=> RMB-31 foreign key documentation and performance test

domain-models-runtime/src/main/java/org/folio/rest/persist/PgExceptionUtil.java, domain-models-runtime/src/test/java/org/folio/rest/persist/PgExceptionUtilTest.java
moved from https://github.com/folio-org/mod-inventory-storage/blob/e65b6aba85e8c92a089b4d60a31b358245068ebd/src/main/java/org/folio/rest/persist/DatabaseExceptionUtils.java
=> add PgExceptionUtil.java

.gitignore, domain-models-runtime/src/main/java/org/folio/rest/RestVerticle.java
If `application/x-www-form-urlencoded` is POST-ed, this will merge it into params. Needed by mod-login-saml callback handler.
=> MODLOGIN-8 Register bodyhandler for simple form data too

Jenkinsfile, README.md, domain-models-api-aspects/src/main/java/org/folio/rest/annotations/SchemaMapper2.aj, domain-models-api-interfaces/pom.xml, domain-models-api-interfaces/raml/book.schema, domain-models-api-interfaces/raml/sample.raml, domain-models-interface-extensions/pom.xml, domain-models-interface-extensions/src/main/java/org/folio/rest/tools/JsonSchemaPojoUtil.java, domain-models-runtime/src/main/resources/templates/db_scripts/metadata/metadata.sql, domain-models-runtime/src/main/resources/templates/facets/base_facet_query.ftl
=> FOLIO-351 tidy 3

domain-models-runtime/pom.xml, domain-models-runtime/src/main/resources/templates/db_scripts/examples/schema.json.example
=> FOLIO-351 tidy 5

domain-models-runtime/src/main/java/org/folio/rest/RestVerticle.java
In mod-codex-mux I  multiple instances of my "mock" module .. This made it work for me.
=> Fix running multiple verticles

domain-models-runtime/src/main/java/org/folio/rest/impl/AdminAPI.java, domain-models-runtime/src/main/java/org/folio/rest/persist/PostgresClient.java
=> importSQL tenant sensitive

domain-models-api-aspects/pom.xml, domain-models-api-interfaces/pom.xml, domain-models-interface-extensions/pom.xml, domain-models-runtime/pom.xml, pom.xml, postgres-runner/pom.xml, rules/pom.xml, testing/pom.xml, util/pom.xml
Major changes:
* RMB-103: Schema dereferencing requires a ramls/ directory with the raml and schema files.
* CQLPG-29 "sortBy field" sorts by null (cql2pgjson:1.3.3)
=> Release 16.0.3

NEWS.md
The date used is the point of which the tag is made.
=> Dates in news file

domain-models-runtime/pom.xml, domain-models-runtime/src/main/java/org/folio/rest/persist/PostgresClient.java, domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientTest.java, pom.xml
Also fix 2 Exception.printStackTrace() vulnerabilities (sonar).
=> Move PostgresClient.main to PostgresClientTest.parseQuery

NEWS.md
Fix broken formatting in NEWS.md
=> Format NEWS.md

pom.xml, util/pom.xml, util/src/main/java/org/folio/util/StringUtil.java, util/src/test/java/org/folio/HttpStatusTest.java, util/src/test/java/org/folio/util/IoUtilTest.java, util/src/test/java/org/folio/util/ResourceUtilTest.java, util/src/test/java/org/folio/util/StringUtilTest.java
Convert unit tests to JUnit5 in the util submodule.
=> RMB-153: Add folio/util/StringUtil.urlencode(String)

domain-models-api-interfaces/ramls/admin.raml
Testing generate api-docs for each version
=> FOLIO-1392 generate api-docs each version

domain-models-interface-extensions/src/main/java/org/folio/rest/tools/GenerateRunner.java, domain-models-interface-extensions/src/test/java/org/folio/rest/tools/GenerateRunnerTest.java
Changing scheme to use raml_files to determine area of schemas and
ramls to copy.
=> Minor regression with RMB-203 in mod-configuration

domain-models-api-interfaces/ramls/book.schema, domain-models-api-interfaces/ramls/bulk.schema, domain-models-api-interfaces/ramls/bulks.schema, domain-models-api-interfaces/ramls/job.schema, domain-models-api-interfaces/ramls/jobs.schema, domain-models-api-interfaces/ramls/jobs_conf.schema, domain-models-api-interfaces/ramls/jobs_confs.schema, domain-models-api-interfaces/ramls/sample.raml
Use pathname as schema $ref again
=> RMB-203 raml1 pathname ref

README.md
First pass at updating body of the README.
(Already have the top-level Upgrade notes.)
More to come.
=> RMB-213 update readme 1

README.md
=> RMB-213 update readme 2

README.md, domain-models-runtime/src/main/resources/apidocs/NOTICE.txt, domain-models-runtime/src/main/resources/apidocs/scripts/api-console.js, domain-models-runtime/src/main/resources/apidocs/styles/api-console-dark-theme.css, domain-models-runtime/src/main/resources/apidocs/styles/api-console-light-theme.css
To mulesoft/api-console-3.0.30
=> RMB-239 upgrade local apidocs

NEWS.md, domain-models-interface-extensions/src/main/java/org/folio/rest/tools/plugins/CustomTypeAnnotator.java, domain-models-interface-extensions/src/test/java/org/folio/rest/tools/GenerateRunnerTest.java, domain-models-interface-extensions/src/test/resources/schemas/elementAnnotationTest.schema
=> FOLIO-351 tidy 6

domain-models-runtime/src/main/java/org/folio/rest/persist/PostgresClient.java, domain-models-runtime/src/main/java/org/folio/rest/persist/facets/ParsedQuery.java, domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientTest.java
Resolves https://issues.folio.org/browse/RMB-96 and https://issues.folio.org/browse/RMB-175.
This snapshot was tested against mod-users and mod-notify. I am now going to attempt upgrading some other modules and test.
=> RMB-96: count query RMB-175: query limit

NEWS.md, domain-models-api-interfaces/ramls/book.schema, domain-models-api-interfaces/ramls/bulk.schema, domain-models-api-interfaces/ramls/bulks.schema, domain-models-api-interfaces/ramls/dbTemplate.schema, domain-models-api-interfaces/ramls/job.schema, domain-models-api-interfaces/ramls/jobs.schema, domain-models-api-interfaces/ramls/jobs_conf.schema, domain-models-api-interfaces/ramls/jobs_confs.schema, domain-models-api-interfaces/ramls/last_modified.schema, domain-models-api-interfaces/ramls/parameter.schema, domain-models-runtime/src/main/java/org/folio/rest/persist/PostgresClient.java, domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientIT.java
* Initialize moduleName in the constructor (RMB-230)
* Initialize vertx, tenantId, schemaName in the constructor.
* Make variables final: MODULE_NAME, vertx, tenantId, schemaName
* Replace convertToPsqlStandard(tenantId) by schemaName
* Add getTenantId() and getSchemaName() (RMB-254)
=> RMB-230: RMB-254: PostgresClient: init moduleName, getTenantId(), getSchemaName()

domain-models-runtime/src/main/java/org/folio/rest/persist/PostgresClient.java
Resolves https://issues.folio.org/browse/RMB-255
- abstracted building select QueryHelper
- decomposed serialize results to be able to deserialize individual row
- multi-purposed inner class ResultsHelper to accommodate streaming
- push stream through stream handler
- provide reply handler for stream end handling
This PR should be accompanied by https://github.com/folio-org/raml/pull/108
=> provide streaming get from PostgresClient

domain-models-runtime/src/main/java/org/folio/rest/persist/PostgresClient.java
Related test branch on mod-users: https://github.com/folio-org/mod-users/tree/MODUSERS-100-excessive-test-invalid-uuid
=> close connection on count query fail or throws exception

domain-models-runtime/src/main/java/org/folio/rest/impl/TenantAPI.java
Use new tenant init definition (from shared-raml) and return 200 if upgrade is OK; 201 if install (new) is OK.
=> Rmb 296 tenant init reference data

domain-models-runtime/src/main/java/org/folio/rest/persist/PgUtil.java, domain-models-runtime/src/test/java/org/folio/rest/jaxrs/model/User.java, domain-models-runtime/src/test/java/org/folio/rest/jaxrs/model/UserdataCollection.java, domain-models-runtime/src/test/java/org/folio/rest/jaxrs/model/Users.java, domain-models-runtime/src/test/java/org/folio/rest/jaxrs/model/UsersGetOrder.java, domain-models-runtime/src/test/java/org/folio/rest/persist/PgUtilIT.java
=> RMB-288: Move StorageHelper to PgUtil - CRUD boilerplate code

domain-models-interface-extensions/src/main/java/org/folio/rest/tools/plugins/ResourceMethodExtensionPlugin.java
=> Validate URI parameters RMB-311

domain-models-runtime/src/main/java/org/folio/rest/persist/PostgresClient.java, domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientIT.java
Sorry.. some formatting also part of this..
=> Add PostClient.saveBatch variant with SQLConnection RMB-354

domain-models-runtime/src/test/java/org/folio/rest/persist/ddlgen/SchemaMakerTest.java
This is a JUnit4 class, it should not use assertTrue from JUnit5/Jupiter.
=> Use assertTrue from JUnit4.

domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientIT.java
=> RMB-390: Unit tests fail (24.1.0-SNAPSHOT) f_unaccent

domain-models-runtime/src/main/java/org/folio/rest/persist/PgUtil.java, domain-models-runtime/src/test/java/org/folio/rest/persist/PgUtilIT.java
of respond201WithApplicationJson
=> RMB-401: PgUtil.post: Object or POJO type for entity parameter

cql2pgjson/README.md, cql2pgjson/src/main/java/org/folio/cql2pgjson/util/Cql2SqlUtil.java
update to documentation from previously merged branch
=> Rmb 391 readme update

domain-models-runtime/src/main/java/org/folio/rest/persist/PostgresClient.java, domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientIT.java
=> RMB-405: PostgresClient.save: Create random UUID if id is missing

cql2pgjson/src/main/java/org/folio/cql2pgjson/CQL2PgJSON.java, cql2pgjson/src/test/java/org/folio/cql2pgjson/ForeignKeyGenerationTest.java
=> Reject foreign table processing if current table is unknown.

README.md
simple pull request to update documentation
=> Added additional details in README regarding cross table index usage

README.md
=> RMB-450: Updated Documentation for Cross Table Query

util/src/main/java/org/folio/HttpStatus.java
rename from HTTP_VALIDATION_ERROR to HTTP_UNPROCESSABLE_ENTITY
=> RMB-445: Rename 422 HttpStatus enum  to HTTP_UNPROCESSABLE_ENTITY

DB-schema-migration.md, README.md, cql2pgjson/src/test/resources/templates/db_scripts/foreignKeyWithinCorrectTarget.json, domain-models-runtime/pom.xml, pom.xml, sample2/src/test/java/org/folio/rest/impl/APITests.java
Minor tweaks for presentation, readability, and consistency.
No actual code changes.
=> FOLIO-398 tidy

DB-schema-migration.md, README.md, doc/README.md
Tweaks for readability and presentation.
Link from other documentation.
=> FOLIO-2169 tidy DB Schema migration doc

README.md
Part of the description of `ginIndex` is confusing. Is this explanation better?
=> Clarify description of ginIndex

domain-models-runtime-it/src/test/java/org/folio/rest/BeesApiTest.java, domain-models-runtime/src/main/java/org/folio/rest/RestVerticle.java
=> Fix RMB echoes all headers RMB-478

cql2pgjson/src/test/java/org/folio/cql2pgjson/CompoundIndexIT.java, cql2pgjson/src/test/java/org/folio/cql2pgjson/CompoundIndexTest.java, cql2pgjson/src/test/resources/compoundIndex.sql, cql2pgjson/src/test/resources/templates/db_scripts/compoundIndex.json, dbschema/src/main/java/org/folio/rest/persist/ddlgen/Index.java, dbschema/src/test/java/org/folio/rest/persist/ddlgen/IndexTest.java
I fixed the code problems related to index paths and spaces surrounding the comma.  I also added unit test and integration test for all the new cases as well as adding new tests to index to fill in code coverage.
=> Rmb 470 and RMB 469

domain-models-runtime/src/main/java/org/folio/rest/tools/monitor/StatsTracker.java
Race condition example:
```
java.lang.IllegalArgumentException: A metric named org.folio.rest.persist.PostgresClientget already exists
at com.codahale.metrics.MetricRegistry.register(MetricRegistry.java:97)
at org.folio.rest.tools.monitor.StatsTracker.addStatElement(StatsTracker.java:33)
at org.folio.rest.persist.PostgresClient.lambda$43(PostgresClient.java:2548)
```
=> RMB-427: StatsTracker not being synchronized can fail

domain-models-runtime/pom.xml, domain-models-runtime/src/main/java/org/folio/rest/persist/PgExceptionFacade.java, domain-models-runtime/src/main/java/org/folio/rest/persist/PgExceptionUtil.java, domain-models-runtime/src/main/java/org/folio/rest/tools/utils/ValidationHelper.java, domain-models-runtime/src/test/java/org/folio/rest/persist/PgExceptionUtilTest.java, domain-models-runtime/src/test/java/org/folio/rest/tools/utils/ValidationHelperTest.java
Changed to vertx-mysql-postgresql-client-jasync:3.8.2-FOLIO-2, and fixed compilation errors. Build fine on my local laptop but Jenkins seems to have issue to download com.github.jasync-sql:jasync-postgresql:jar:0.9.51
=> RmB-485 Update to vertx-mysql-postgresql-client-jasync 3.8.2-FOLIO-2

domain-models-runtime/pom.xml
Saw this issue trying when enabling logging for included projects such as postgresql-embedded
=> Fix no static logger for SLF4J RMB-488

domain-models-runtime/src/main/java/org/folio/rest/persist/cql/CQLWrapper.java, domain-models-runtime/src/test/java/org/folio/rest/persist/cql/CQLWrapperTest.java
Ensure existing query is grouped () before applying operator
with added query.
=> Fix CQLWrapper.addWrapper not left associative RMB-493

cql2pgjson/src/main/java/org/folio/cql2pgjson/CQL2PgJSON.java, cql2pgjson/src/test/java/org/folio/cql2pgjson/CompoundIndexTest.java, dbschema/src/main/java/org/folio/cql2pgjson/util/Cql2PgUtil.java, dbschema/src/main/java/org/folio/rest/persist/ddlgen/Index.java, dbschema/src/test/java/org/folio/rest/persist/ddlgen/IndexTest.java, domain-models-runtime/src/test/java/org/folio/rest/persist/ddlgen/SchemaMakerTest.java
difference in generation and query resolved by pushing wrapping into the index function.
=> RMB-536: Missing f_unaccent for compound fields full text index

cql2pgjson/src/main/java/org/folio/cql2pgjson/CQL2PgJSON.java, cql2pgjson/src/test/java/org/folio/cql2pgjson/CompoundIndexTest.java, dbschema/src/main/java/org/folio/rest/persist/ddlgen/Index.java, dbschema/src/test/java/org/folio/rest/persist/ddlgen/IndexTest.java, domain-models-runtime/src/test/java/org/folio/rest/persist/ddlgen/SchemaMakerTest.java
fixed mistake in wrapping logic for index.  I took the fixes I applied in another branch and made them here.  This will cause merge errors, but they should be easily resolved.
=> RMB-536: Another bugfix for index wrapping

cql2pgjson/src/main/java/org/folio/cql2pgjson/util/Cql2SqlUtil.java, cql2pgjson/src/test/java/org/folio/cql2pgjson/util/Cql2SqlUtilTest.java
cherry-pick #584 RMB-537-f_unaccent-single-quote into 29.1
=> RMB-537: Fix f_unaccent single quote fullText tsquery sql injection (29.1 backport)

cql2pgjson/src/main/java/org/folio/cql2pgjson/CQL2PgJSON.java, cql2pgjson/src/test/java/org/folio/cql2pgjson/CompoundIndexTest.java, dbschema/src/main/java/org/folio/rest/persist/ddlgen/Index.java, dbschema/src/test/java/org/folio/rest/persist/ddlgen/IndexTest.java, domain-models-runtime/src/test/java/org/folio/rest/persist/ddlgen/SchemaMakerTest.java
Merge pull request #586 from folio-org/RMB-533_bug_fix
=> RMB-533/RMB-536: Another bugfix for index wrapping - 29.1 backport

domain-models-runtime/src/main/java/org/folio/rest/persist/PgUtil.java
Merge pull request #595 from folio-org/RMB-541-getWithOptimizedSql-left600
=> RMB-541: PgUtil.getWithOptimizedSql with left(..., 600) - 29.1 backport

domain-models-runtime/src/test/java/org/folio/rest/impl/BooksDemoAPI.java
Now, only one call to PgUtil.streamGet.
=> Fix Unit tests in Jenkins fail (streamGet) RMB-580

domain-models-runtime/src/main/java/org/folio/rest/persist/PostgresClient.java, domain-models-runtime/src/main/resources/templates/db_scripts/general_functions.ftl, domain-models-runtime/src/main/resources/templates/db_scripts/main.ftl, domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientTest.java, domain-models-runtime/src/test/java/org/folio/rest/persist/ddlgen/SchemaMakerIT.java, pom.xml
* general_functions.ftl: Move public.f_unaccent to ${myuniversity}_${mymodule}.f_unaccent(text)
* main.ftl: SET search_path TO ${myuniversity}_${mymodule}, public
* main.ftl: Fix functions calls with "public." in indexes
* mail.ftl: Update "rmbVersion" and "moduleVersion" in table rmb_internal
* PostgresClient.runSqlFile: Use PostgreSQL dollar quoting to detect functions and "DO $$ ... $$;".
=> RMB-583: Move f_unaccent/concat* from public to schema, fix search_path

domain-models-runtime/src/main/java/org/folio/rest/impl/TenantAPI.java, domain-models-runtime/src/main/resources/templates/db_scripts/main.ftl
After tenant create or tenant upgrade set the values of the
moduleVersion and rmbVersion variables in rmb_internal table
to the new values.
=> RMB-164: Incorrect moduleVersion and rmbVersion in rmb_internal table

README.md, doc/upgrading.md, domain-models-api-interfaces/pom.xml, domain-models-runtime/pom.xml, rules/pom.xml, sample/pom.xml, sample2/pom.xml
Add usage instructions to README.md.
Add pom.ml fix suggestions to upgrade.md.
Fix Maven ${} variable replacement in src/main/resources in each RMB pom.xml.
=> RMB-588: Explain Maven and RMB ${} variable replacement

README.md, doc/upgrading.md
In README and upgrading notes.
=> FOLIO-398 Fix text typos, punctuation, readability

cql2pgjson/src/main/java/org/folio/cql2pgjson/CQL2PgJSON.java
See https://issues.folio.org/browse/UIIN-1064?focusedCommentId=74329&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-74329
=> Don't warn about missing full text index if SQL = "true"

domain-models-runtime/src/main/java/org/folio/rest/persist/PgUtil.java
Use WITH totalCount to extract (and run only once) the total count subquery that PostgreSQL runs for each returned row in some environments.
=> RMB-613 SQL query regression fix

domain-models-runtime/src/main/java/org/folio/rest/persist/PostgresClient.java, domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientIT.java
Create PostgresClient.upsertBatch similar to the existing PostgresClient.saveBatch methods.
If the record with the id already exists the new one overwrites the old one by using
INSERT ... ON CONFLICT (id) DO UPDATE.
=> RMB-600: PostgresClient.upsertBatch

doc/upgrading.md, domain-models-runtime/src/main/java/org/folio/rest/persist/PostgresClient.java, domain-models-runtime/src/test/java/org/folio/rest/persist/LoadGeneralFunctions.java, domain-models-runtime/src/test/java/org/folio/rest/persist/PgUtilIT.java, domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientIT.java, domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientITBase.java, domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientTest.java, pom.xml, sample/pom.xml, sample2/pom.xml
Needs a little more work in "fake" connections.. so that execute fails with error (rather than query method returning null).
=> Update to Vert.x 3.9.0 RMB-619

pom.xml
=> Drop unused org.apache.httpcomponents:httpclient dependency

domain-models-runtime/src/main/java/org/folio/rest/persist/PostgresClient.java, domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientIT.java
Was removed as part of RMB-246 work in RMB 30.0.0.
=> Provide getConnectionConfig again RMB-634

domain-models-runtime/src/main/java/org/folio/rest/persist/PgUtil.java, domain-models-runtime/src/test/java/org/folio/DemoRamlRestTest.java, domain-models-runtime/src/test/java/org/folio/rest/impl/BooksDemoAPI.java, domain-models-runtime/src/test/java/org/folio/rest/persist/PgUtilIT.java
We do need a builder pattern here.. Many arguments and many variants lead to a combinatorial explosion.
=> streamGet, getWithOptimizedSql wo queryTimeout RMB-639

.gitignore, README.md, domain-models-api-interfaces/ramls/sample.raml, domain-models-runtime-it/ramls/wrappedboolean.raml, domain-models-runtime-it/ramls/wrappedinteger.raml, domain-models-runtime-it/src/main/java/org/folio/rest/impl/WrappedBooleanApi.java, domain-models-runtime-it/src/main/java/org/folio/rest/impl/WrappedIntegerApi.java, domain-models-runtime-it/src/test/java/org/folio/rest/WrappedBooleanApiTest.java, domain-models-runtime-it/src/test/java/org/folio/rest/WrappedIntegerApiTest.java, domain-models-runtime/src/main/java/org/folio/rest/RestVerticle.java, domain-models-runtime/src/test/java/org/folio/rest/impl/BooksDemoAPI.java
requires https://github.com/folio-org/raml/pull/125
=> RMB-643: Wrapped query parameter types

NEWS.md, cql2pgjson-cli/pom.xml, cql2pgjson/pom.xml, dbschema/pom.xml, domain-models-api-aspects/pom.xml, domain-models-api-interfaces/pom.xml, domain-models-interface-extensions/pom.xml, domain-models-runtime-it/pom.xml, domain-models-runtime/pom.xml, pom.xml, testing/pom.xml, util/pom.xml
* [RMB-648](https://issues.folio.org/browse/RMB-648) org.hibernate:hibernate-validator vulnerability
* [RMB-649](https://issues.folio.org/browse/RMB-649) Remove duplicate foreign key constraints for unchanged tables
* [RMB-650](https://issues.folio.org/browse/RMB-650) Client generator should support Date query parameter
=> FOLREL-399: Release RMB v30.2.0

domain-models-interface-extensions/src/main/java/org/folio/rest/tools/ClientGenerator.java, domain-models-interface-extensions/src/test/java/org/folio/rest/tools/ClientGeneratorTest.java, domain-models-runtime/src/test/java/org/folio/DemoRamlRestTest.java
remove second fration and zone offset
=> RMB-650: Simplify query parameter date time format

domain-models-runtime/src/main/resources/templates/db_scripts/extensions.ftl
https://issues.folio.org/browse/RMB-671 drops PostgreSQL extension pg_trgm
if it has been created in a wrong schema (like pg_catalog) to then recreate
it in the correct public schema.
The bug is that this drops all indexes that use pg_trgm (cascade) and the
indexes are not recreated.
Steve Osguthorpe points out that PostgreSQL has
`ALTER EXTENSION pg_trgm SET SCHEMA public` that moves the extension
without dropping indexes, PostgreSQL automatically changes all extension
usages to use the new extension location.
`ALTER EXTENSION pg_trgm` does not have an `ALTER EXTENSION IF EXISTS pg_trgm`
option, this needs to be handled by exception catching.
=> RMB-675: Move pg_trgm from wrong to public schema, don't drop & recreate

domain-models-runtime/src/main/java/org/folio/rest/persist/PostgresClient.java, domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientIT.java, domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientTest.java
Fix bug that has been introduced in v22.0.0:
https://github.com/folio-org/raml-module-builder/commit/84d969dd4d9bf20bf9360090738960652a625132
Rename total to estimatedTotal.
=> RMB-684 no records when offset value > estimated totalRecords

domain-models-runtime/src/main/resources/templates/db_scripts/create.ftl, domain-models-runtime/src/test/java/org/folio/rest/persist/ddlgen/SchemaMakerTest.java
Besides the test in code here I tried upgrading mod-inventory-storage 19.1.5-SNAPSHOT to newest in master. Was able to reproduce the issue and able to see that this fixes it.
=> Always create rmb_job table if it does not exist RMB-779

doc/upgrading.md
Part of https://issues.folio.org/browse/RMB-778 Optimistic locking upgrade notes
=> RMB-778 Add a link to optimistic locking

README.md, doc/upgrading.md
Add links related to optimistic locking logging. Also made minor formatting adjustments.
=> RMB-778: Add optimistic locking logging doc

domain-models-runtime/src/main/java/org/folio/rest/persist/PostgresClient.java, domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientIT.java, domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientMockTest.java, domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientTransactionsIT.java
New public PostgresClient methods:
```java
<T> Future<T> withTransaction(Function<PgConnection, Future<T>> function)
<T> Future<T> withConnection(Function<PgConnection, Future<T>> function)
```
=> PostgresClient.withTransaction RMB-741

README.md, domain-models-runtime/src/main/resources/templates/db_scripts/optimistic_locking.ftl
See https://issues.folio.org/browse/RMB-786
=> RMB-786 change OL notice level

domain-models-runtime/pom.xml
https://app.snyk.io/vuln/SNYK-JAVA-ORGFREEMARKER-1076795
=> Freemarker 2.3.31, fixing Server-side Template Injection (SSTI)

README.md
Please see https://issues.folio.org/browse/RMB-787 document guidance on API and Schema versioning for OptimisticLocking
The final decision from @skoczko is in this [comment](https://issues.folio.org/browse/RMB-787?focusedCommentId=98650&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-98650).
=> RMB-787 OL API and schema versioning guidance

README.md, domain-models-runtime/src/main/java/org/folio/rest/persist/LoadConfs.java, domain-models-runtime/src/test/java/org/folio/rest/persist/LoadConfsTest.java
* Remove undocumented configuration loading from URL to close
this security hole
* Expand db_connection documentation
* LoadConfs code cleanup and unit tests
=> db_connection LoadConfs code and documentation cleanup

domain-models-runtime/src/test/java/org/folio/rest/tools/utils/TenantInitTest.java
"Connection refused" is a locale dependent String; the unit test
fails under other locales like German.
Replace by checking the Exception class.
=> Replace "Connection refused" by ConnectException

domain-models-runtime/src/main/java/org/folio/rest/persist/PostgresClient.java, domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientIT.java
Reported on
https://sonarcloud.io/project/issues?id=org.folio%3Araml-module-builder&issues=AXf_mq3KcJeCOCmzGcZb&open=AXf_mq3KcJeCOCmzGcZb&pullRequest=875
=> Properly handle NPE in runSQLFile

domain-models-runtime/src/main/java/org/folio/rest/persist/Conn.java, domain-models-runtime/src/main/java/org/folio/rest/persist/PostgresClient.java, domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientIT.java
This also extracts duplicate code into
withConn(AsyncResult<SQLConnection>, Function<Conn, Future<T>>).
=> RMB-602: PostgresClient.update futurisation

domain-models-runtime/src/test/java/org/folio/rest/persist/ConnIT.java
In about 10% of all builds ConnIT.getByIdForUpdate fails because
of a race condition. The value is still b but should be c.
It happens on Jenkins and locally.
This fix avoids the race condition by polling until success.
=> Fix ConnIT.getByIdForUpdate race condition

cql2pgjson/pom.xml, dbschema/pom.xml
Backporting from master to b32.2
=> RMB-823: Update maven.indexdata.com URL to use https

cql2pgjson/pom.xml, domain-models-runtime/pom.xml, pom.xml
https://github.com/advisories/GHSA-gwrp-pvrq-jmwv
=> Update commons-io from 2.6 to 2.8.0 RMB-833

domain-models-runtime/src/main/java/org/folio/rest/tools/parser/JsonPathParser.java
At line 277 & 294 , parent may throw NullPointerException. so added a null check condition.
=> Rmb 850 json parser null condition check

domain-models-runtime/src/main/java/org/folio/rest/tools/parser/JsonPathParser.java
Line:366- if(subPathsList[i+1].matches(".*\\[.*?\\].*"))  dropped. 
As per my understanding above regex matches string with in square brackets.
=> Dropped Regex

pom.xml
=> Upgrade testcontainers to 1.16.2

cql2pgjson/src/main/java/org/folio/cql2pgjson/CQL2PgJSON.java
Fixes CQLPG-105 = https://issues.folio.org/browse/RMB-881
=> RMB-881: Reduce logging level of loadDbSchema

domain-models-runtime/src/main/java/org/folio/rest/tools/utils/TenantLoading.java, domain-models-runtime/src/test/java/org/folio/rest/tools/utils/TenantLoadingTest.java
When upgrading a module using TenantLoading it might be desired not
to overwrite existing data. When installing a module for a tenant loading
reference and sample data should be idempotent so that it can be run
twice, for example after a failure.
Solution: Add withPostIgnore() to TenantLoading that ignores
any 4xx HTTP status codes.
=> RMB-886: TenantLoading withPostIgnore(), no overwrite on upgrade

domain-models-runtime/src/main/java/org/folio/rest/RestRouting.java
https://issues.folio.org/browse/RMB-890
=> Fix no context parameters logged RMB-890

doc/upgrading.md, domain-models-runtime/src/main/java/org/folio/rest/persist/PostgresClient.java, domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientIT.java, domain-models-runtime/src/test/java/org/folio/rest/persist/PostgresClientTest.java
https://issues.folio.org/browse/RMB-885
=> Remove deprecated get, streamGet methods RMB-885

cql2pgjson/src/main/java/org/folio/cql2pgjson/CQL2PgJSON.java, cql2pgjson/src/test/java/org/folio/cql2pgjson/CQL2PgJSONTest.java
Steps to Reproduce:
1. Run CQL query permanentLocationId == "" against inventory item API
2. Run CQL query cql.allRecords=1 NOT permanentLocationId == "" against inventory item API
Expected Results:
1. Should match no record.
2. Should match all records.
Actual Results:
1. Matches all records where permanentLocationId is defined.
2. Matches all records where permanentLocationId is not defined.
RMB Documentation
https://github.com/folio-org/raml-module-builder#cql-matching-undefined-or-empty-values
Fix the implementation to match the documentation.
Note that matching an empty string properly works for a string field that
is not an RMB managed uuid field.
=> RMB-932: Broken empty string matching: uuidfield == ""
